import numpy as np
from numpy import einsum

def H_0(Fock_Trans, V_Trans, t1, t2, f, g, o, v):

    Fock_Trans[o,o] += 1.0 * einsum('ij->ij', f[o, o])
    Fock_Trans[o,v] += 1.0 * einsum('ia->ia', f[o, v])
    Fock_Trans[v,v] += 1.0 * einsum('ab->ab', f[v, v])
    V_Trans[o,o,o,o] += 1.0 * einsum('ijkl->ijkl', g[o, o, o, o])
    V_Trans[o,o,o,v] += 1.0 * einsum('ijka->ijka', g[o, o, o, v])
    V_Trans[o,o,v,v] += 1.0 * einsum('ijab->ijab', g[o, o, v, v])
    V_Trans[o,v,o,v] += 1.0 * einsum('iajb->iajb', g[o, v, o, v])
    V_Trans[o,v,v,v] += 1.0 * einsum('iabc->iabc', g[o, v, v, v])
    V_Trans[v,v,v,v] += 1.0 * einsum('abcd->abcd', g[v, v, v, v])

def F_1(Fock_Trans, V_Trans, t1, t2, f, g, o, v):

    #   HH  ------------------------------------------------------------
    #   1.0 * f(i, e) * t1(e, j)
    Fock_Trans[o,o] += 1.0 * einsum('ie,ej->ij', f[o, v], t1, optimize=True)
    #   1.0 * t1(e, i) * f(j, e)
    Fock_Trans[o,o] += 1.0 * einsum('ei,je->ij', t1, f[o, v], optimize=True)

    #   PP  ------------------------------------------------------------
    #   -1.0 * f(m, b) * t1(a, m)
    Fock_Trans[v,v] += -1.0 * einsum('mb,am->ab', f[o, v], t1, optimize=True)
    #   -1.0 * t1(b, m) * f(m, a)
    Fock_Trans[v,v] += -1.0 * einsum('bm,ma->ab', t1, f[o, v], optimize=True)

    #   HP  ------------------------------------------------------------
    #   -1.0 * f1_OO(m, i) * t1(a, m)
    Fock_Trans[o,v] += -1.0 * einsum('mi,am->ia', f[o, o], t1, optimize=True)
    #   1.0 * f1_VV(a, e) * t1(e, i)
    Fock_Trans[o,v] += 1.0 * einsum('ae,ei->ia', f[v, v], t1, optimize=True)
    #   1.0 * f1_OV(m, e) * t2(a, e, i, m)
    Fock_Trans[o,v] += 1.0 * einsum('me,aeim->ia', f[o, v], t2, optimize=True)

    #   HHHH -----------------------------------------------------------
    #   NO TERMS

    #   HHHP -----------------------------------------------------------
    #   1.0 * f1_OV(k, e) * t2(a, e, j, i)
    V_Trans[o,o,o,v] += 1.0 * einsum('ke,aeji->ijka', f[o, v], t2, optimize=True)

    #   HHPP -----------------------------------------------------------
    #   1.0 * f1_OO(m, i) * t2(a, b, j, m)
    V_Trans[o,o,v,v] += 1.0 * einsum('mi,abjm->ijab', f[o, o], t2, optimize=True)
    #   -1.0 * f1_VV(a, e) * t2(b, e, i, j)
    V_Trans[o,o,v,v] += -1.0 * einsum('ae,beij->ijab', f[v, v], t2, optimize=True)
    #   -1.0 * f1_OO(m, j) * t2(a, b, i, m)
    V_Trans[o,o,v,v] += -1.0 * einsum('mj,abim->ijab', f[o, o], t2, optimize=True)
    #   1.0 * f1_VV(b, e) * t2(a, e, i, j)
    V_Trans[o,o,v,v] += 1.0 * einsum('be,aeij->ijab', f[v, v], t2, optimize=True)

    #   HPHP -----------------------------------------------------------
    #   NO TERMS

    #   HPPP -----------------------------------------------------------
    #   -1.0 * f1_OV(m, a) * t2(b, c, i, m)
    V_Trans[o,v,v,v] += -1.0 * einsum('ma,bcim->iabc', f[o, v], t2, optimize=True)

    #   PPPP -----------------------------------------------------------
    #   NO TERMS

def V_1(Fock_Trans, V_Trans, t1, t2, f, g, o, v):

    #   HH  ------------------------------------------------------------
    #   -1.0 * v2ijka(m, i, j, e) * t1(e, m)
    Fock_Trans[o,o] += -1.0 * einsum('mije,em->ij', g[o, o, o, v], t1, optimize=True)
    #   -(1.0/2.0) * v2ijab(m, i, e, f) * t2(e, f, j, m)
    Fock_Trans[o,o] += -0.5 * einsum('mief,efjm->ij', g[o, o, v, v], t2, optimize=True)
    #   -1.0 * t1(e, m) * v2ijka(m, j, i, e)
    Fock_Trans[o,o] += -1.0 * einsum('em,mjie->ij', t1, g[o, o, o, v], optimize=True)
    #   -(1.0/2.0) * t2(e, f, m, i) * v2ijab(j, m, e, f)
    Fock_Trans[o,o] += -0.5 * einsum('efmi,jmef->ij', t2, g[o, o, v, v], optimize=True)

    #   PP  ------------------------------------------------------------
    #   -1.0 * v2iabc(m, a, b, e) * t1(e, m)
    Fock_Trans[v,v] += -1.0 * einsum('mabe,em->ab', g[o, v, v, v], t1, optimize=False)
    #   (1.0/2.0) * v2ijab(m, n, e, b) * t2(a, e, m, n)
    Fock_Trans[v,v] += 0.5 * einsum('mneb,aemn->ab', g[o, o, v, v], t2, optimize=True)
    #   -1.0 * t1(e, m) * v2iabc(m, b, a, e)
    Fock_Trans[v,v] += -1.0 * einsum('em,mbae->ab', t1, g[o, v, v, v], optimize=True)
    #   (1.0/2.0) * t2(e, b, m, n) * v2ijab(m, n, a, e)
    Fock_Trans[v,v] += 0.5 * einsum('ebmn,mnae->ab', t2, g[o, o, v, v], optimize=True)

    #   PH  ------------------------------------------------------------
    #   -1.0 * v2iajb(i, e, m, a) * t1(e, m)
    Fock_Trans[o,v] += -1.0 * einsum('iema,em->ia', g[o, v, o, v], t1, optimize=True)
    #   -(1.0/2.0) * v2ijka(m, n, i, e) * t2(a, e, m, n)
    Fock_Trans[o,v] += -0.5 * einsum('mnie,aemn->ia', g[o, o, o, v], t2, optimize=True)
    #   (1.0/2.0) * v2iabc(m, a, f, e) * t2(e, f, i, m)
    Fock_Trans[o,v] += 0.5 * einsum('mafe,efim->ia', g[o, v, v, v], t2, optimize=True)
    #   1.0 * t1(e, m) * v2ijab(i, m, a, e)
    Fock_Trans[o,v] += 1.0 * einsum('em,imae->ia', t1, g[o, o, v ,v], optimize=True)

    #   HHHH -----------------------------------------------------------
    #   1.0 * v2ijka(i, j, k, e) * t1(e, l)
    V_Trans[o,o,o,o] += 1.0 * einsum('ijke,el->ijkl', g[o, o, o, v], t1, optimize=True)
    #   -1.0 * v2ijka(i, j, l, e) * t1(e, k)
    V_Trans[o,o,o,o] += -1.0 * einsum('ijle,ek->ijkl', g[o, o, o, v], t1, optimize=True)
    #   (1.0/2.0) * v2ijab(i, j, e, f) * t2(e, f, k, l)
    V_Trans[o,o,o,o] += (1.0/2.0) * einsum('ijef,efkl->ijkl', g[o, o, v, v], t2, optimize=True)
    #   1.0 * t1(e, i) * v2ijka(l, k, j, e)
    V_Trans[o,o,o,o] += 1.0 * einsum('ei,lkje->ijkl', t1, g[o, o, o, v], optimize=True)
    #   -1.0 * t1(e, j) * v2ijka(l, k, i, e)
    V_Trans[o,o,o,o] += -1.0 * einsum('ej,lkie->ijkl', t1, g[o, o, o, v], optimize=True)
    #   (1.0/2.0) * t2(e, f, i, j) * v2ijab(k, l, e, f)
    V_Trans[o,o,o,o] += (1.0/2.0) * einsum('efij,klef->ijkl', t2, g[o, o, v, v], optimize=True)

    #   HHHP -----------------------------------------------------------
    #   -1.0 * v2iajb(k, a, j, e) * t1(e, i)
    V_Trans[o,o,o,v] += -1.0 * einsum('kaje,ei->ijka', g[o, v, o, v], t1, optimize=True)
    #   -1.0 * v2ijkl(m, k, j, i) * t1(a, m)
    V_Trans[o,o,o,v] += -1.0 * einsum('mkji,am->ijka', g[o, o, o, o], t1, optimize=True)
    #   1.0 * v2iajb(k, a, i, e) * t1(e, j)
    V_Trans[o,o,o,v] += 1.0 * einsum('kaie,ej->ijka', g[o, v, o, v], t1, optimize=True)
    #   1.0 * v2ijka(m, k, j, e) * t2(a, e, i, m)
    V_Trans[o,o,o,v] += 1.0 * einsum('mkje,aeim->ijka', g[o, o, o, v], t2, optimize=True)
    #   (1.0/2.0) * v2iabc(k, a, f, e) * t2(e, f, j, i)
    V_Trans[o,o,o,v] += (1.0/2.0) * einsum('kafe,efji->ijka', g[o, v, v, v], t2, optimize=True)
    #   -1.0 * v2ijka(m, k, i, e) * t2(a, e, j, m)
    V_Trans[o,o,o,v] += -1.0 * einsum('mkie,aejm->ijka', g[o, o, o, v], t2, optimize=True)
    #   1.0 * t1(e, k) * v2ijab(j, i, a, e)
    V_Trans[o,o,o,v] += 1.0 * einsum('ek,jiae->ijka', t1, g[o, o, v, v], optimize=True)

    #   HHPP -----------------------------------------------------------
    #   -1.0 * v2ijka(j, i, m, a) * t1(b, m)
    V_Trans[o,o,v,v] += -1.0 * einsum('jima,bm->ijab', g[o, o, o, v], t1, optimize=True)
    #   1.0 * v2iabc(i, e, a, b) * t1(e, j)
    V_Trans[o,o,v,v] += 1.0 * einsum('ieab,ej->ijab', g[o, v, v, v], t1, optimize=True)
    #   1.0 * v2ijka(j, i, m, b) * t1(a, m)
    V_Trans[o,o,v,v] += 1.0 * einsum('jimb,am->ijab', g[o, o, o, v], t1, optimize=True)
    #   -1.0 * v2iabc(j, e, a, b) * t1(e, i)
    V_Trans[o,o,v,v] += -1.0 * einsum('jeab,ei->ijab', g[o, v, v, v], t1, optimize=True)
    #   -1.0 * v2iajb(i, e, m, a) * t2(b, e, j, m)
    V_Trans[o,o,v,v] += -1.0 * einsum('iema,bejm->ijab', g[o, v, o, v], t2, optimize=True)
    #   (1.0/2.0) * v2ijkl(m, n, i, j) * t2(a, b, m, n)
    V_Trans[o,o,v,v] += (1.0/2.0) * einsum('mnij,abmn->ijab', g[o, o, o, o], t2, optimize=True)
    #   1.0 * v2iajb(i, e, m, b) * t2(a, e, j, m)
    V_Trans[o,o,v,v] += 1.0 * einsum('iemb,aejm->ijab', g[o, v, o, v], t2, optimize=True)
    #   1.0 * v2iajb(j, e, m, a) * t2(b, e, i, m)
    V_Trans[o,o,v,v] += 1.0 * einsum('jema,beim->ijab', g[o, v, o, v], t2, optimize=True)
    #   (1.0/2.0) * v2abcd(a, b, e, f) * t2(e, f, i, j)
    V_Trans[o,o,v,v] += (1.0/2.0) * einsum('abef,efij->ijab', g[v, v, v, v], t2, optimize=True)
    #   -1.0 * v2iajb(j, e, m, b) * t2(a, e, i, m)
    V_Trans[o,o,v,v] += -1.0 * einsum('jemb,aeim->ijab', g[o, v, o, v], t2, optimize=True)

    #   HPHP -----------------------------------------------------------
    #   1.0 * v2ijka(m, i, j, b) * t1(a, m)
    V_Trans[o,v,o,v] += 1.0 * einsum('mijb,am->iajb', g[o, o, o, v], t1, optimize=True)
    #   -1.0 * v2iabc(i, a, b, e) * t1(e, j)
    V_Trans[o,v,o,v] += -1.0 * einsum('iabe,ej->iajb', g[o, v, v, v], t1, optimize=True)
    #   -1.0 * v2ijab(m, i, e, b) * t2(a, e, j, m)
    V_Trans[o,v,o,v] += -1.0 * einsum('mieb,aejm->iajb', g[o, o, v, v], t2, optimize=True)
    #   1.0 * t1(b, m) * v2ijka(m, j, i, a)
    V_Trans[o,v,o,v] += 1.0 * einsum('bm,mjia->iajb', t1, g[o, o, o, v], optimize=True)
    #   -1.0 * t1(e, i) * v2iabc(j, b, a, e)
    V_Trans[o,v,o,v] += -1.0 * einsum('ei,jbae->iajb', t1, g[o, v, v, v], optimize=True)
    #   -1.0 * t2(e, b, m, i) * v2ijab(j, m, a, e)
    V_Trans[o,v,o,v] += -1.0 * einsum('ebmi,jmae->iajb', t2, g[o, o, v, v], optimize=True)

    #   HPPP -----------------------------------------------------------
    #   1.0 * v2iajb(m, b, i, a) * t1(c, m)
    V_Trans[o,v,v,v] += 1.0 * einsum('mbia,cm->iabc', g[o, v, o, v], t1, optimize=True)
    #   1.0 * v2abcd(b, c, e, a) * t1(e, i)
    V_Trans[o,v,v,v] += 1.0 * einsum('bcea,ei->iabc', g[v, v, v, v], t1, optimize=True)
    #   -1.0 * v2iajb(m, c, i, a) * t1(b, m)
    V_Trans[o,v,v,v] += -1.0 * einsum('mcia,bm->iabc', g[o, v, o, v], t1, optimize=True)
    #   1.0 * v2iabc(m, b, a, e) * t2(c, e, i, m)
    V_Trans[o,v,v,v] += 1.0 * einsum('mbae,ceim->iabc', g[o, v, v, v], t2, optimize=True)
    #   (1.0/2.0) * v2ijka(m, n, i, a) * t2(b, c, m, n)
    V_Trans[o,v,v,v] += (1.0/2.0) * einsum('mnia,bcmn->iabc', g[o, o, o, v], t2, optimize=True)
    #   -1.0 * v2iabc(m, c, a, e) * t2(b, e, i, m)
    V_Trans[o,v,v,v] += -1.0 * einsum('mcae,beim->iabc', g[o, v, v, v], t2, optimize=True)
    #   -1.0 * t1(a, m) * v2ijab(i, m, b, c)
    V_Trans[o,v,v,v] += -1.0 * einsum('am,imbc->iabc', t1, g[o, o, v, v], optimize=True)

    #   PPPP -----------------------------------------------------------
    #   -1.0 * v2iabc(m, a, d, c) * t1(b, m)
    V_Trans[v,v,v,v] += -1.0 * einsum('madc,bm->abcd', g[o, v, v, v], t1, optimize=True)
    #   1.0 * v2iabc(m, b, d, c) * t1(a, m)
    V_Trans[v,v,v,v] += 1.0 * einsum('mbdc,am->abcd', g[o, v, v, v], t1, optimize=True)
    #   (1.0/2.0) * v2ijab(m, n, c, d) * t2(a, b, m, n)
    V_Trans[v,v,v,v] += (1.0/2.0) * einsum('mncd,abmn->abcd', g[o, o, v, v], t2, optimize=True)
    #   -1.0 * t1(c, m) * v2iabc(m, d, a, b)
    V_Trans[v,v,v,v] += -1.0 * einsum('cm,mdab->abcd', t1, g[o, v, v, v], optimize=True)
    #   1.0 * t1(d, m) * v2iabc(m, c, a, b)
    V_Trans[v,v,v,v] += 1.0 * einsum('dm,mcab->abcd', t1, g[o, v, v, v], optimize=True)
    #   (1.0/2.0) * t2(c, d, m, n) * v2ijab(m, n, a, b)
    V_Trans[v,v,v,v] += (1.0/2.0) * einsum('cdmn,mnab->abcd', t2, g[o, o, v, v], optimize=True)



def F_2(Fock_Trans, V_Trans, t1, t2, f, g, o, v):

    #   HH  ------------------------------------------------------------
    #   -(1.0/2.0) * t1(e, i) * f(m, j) * t1(e, m)
    Fock_Trans[o,o] += -0.5 * einsum('ei,mj,em->ij', t1, f[o, o], t1, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f(i, m) * t1(e, j)
    Fock_Trans[o,o] += -0.5 * einsum('em,im,ej->ij', t1, f[o, o], t1, optimize=True)
    #   1.0 * t1(e, i) * f(e, f) * t1(f, j)
    Fock_Trans[o,o] += 1.0 * einsum('ei,ef,fj->ij', t1, f[v, v], t1, optimize=True)
    #   (1.0/2.0) * t1(e, i) * f(m, f) * t2(e, f, j, m)
    Fock_Trans[o,o] += 0.5 * einsum('ei,mf,efjm->ij', t1, f[o, v], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f(i, f) * t2(e, f, j, m)
    Fock_Trans[o,o] += -0.5 * einsum('em,if,efjm->ij', t1, f[o, v], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, f, m, i) * f(n, j) * t2(e, f, m, n)
    Fock_Trans[o,o] += -0.25 * einsum('efmi,nj,efmn->ij', t2, f[o, o], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, f, m, n) * f(i, m) * t2(e, f, j, n)
    Fock_Trans[o,o] += -0.25 * einsum('efmn,im,efjn->ij', t2, f[o, o], t2, optimize=True)
    #   (1.0/2.0) * t2(e, f, m, i) * f(n, m) * t2(e, f, j, n)
    Fock_Trans[o,o] += 0.5 * einsum('efmi,nm,efjn->ij', t2, f[o, o], t2, optimize=True)
    #   1.0 * t2(e, f, m, i) * f(e, g) * t2(f, g, j, m)
    Fock_Trans[o,o] += 1.0 * einsum('efmi,eg,fgjm->ij', t2, f[v, v], t2, optimize=True)
    #   -(1.0/2.0) * t2(e, f, m, i) * f(j, e) * t1(f, m)
    Fock_Trans[o,o] += -0.5 * einsum('efmi,je,fm->ij', t2, f[o, v], t1, optimize=True)
    #   (1.0/2.0) * t2(e, f, m, i) * f(m, e) * t1(f, j)
    Fock_Trans[o,o] += 0.5 * einsum('efmi,me,fj->ij', t2, f[o, v], t1, optimize=True)

    #   PP  ------------------------------------------------------------
    #   -(1.0/2.0) * t1(b, m) * f(a, e) * t1(e, m)
    Fock_Trans[v,v] += -0.5 * einsum('bm,ae,em->ab', t1, f[v, v], t1, optimize=True)
    #   1.0 * t1(b, m) * f(n, m) * t1(a, n)
    Fock_Trans[v,v] += 1.0 * einsum('bm,nm,an->ab', t1, f[o, o], t1, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f(e, b) * t1(a, m)
    Fock_Trans[v,v] += -0.5 * einsum('em,eb,am->ab', t1, f[v, v], t1, optimize=True)
    #   -(1.0/2.0) * t1(b, m) * f(n, e) * t2(a, e, m, n)
    Fock_Trans[v,v] += -0.5 * einsum('bm,ne,aemn->ab', t1, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t1(e, m) * f(n, b) * t2(a, e, m, n)
    Fock_Trans[v,v] += 0.5 * einsum('em,nb,aemn->ab', t1, f[o, v], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, b, m, n) * f(a, f) * t2(e, f, m, n)
    Fock_Trans[v,v] += -0.25 * einsum('ebmn,af,efmn->ab', t2, f[v, v], t2, optimize=True)
    #   1.0 * t2(e, b, m, n) * f(o, m) * t2(a, e, n, o)
    Fock_Trans[v,v] += 1.0 * einsum('ebmn,om,aeno->ab', t2, f[o, o], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, f, m, n) * f(e, b) * t2(a, f, m, n)
    Fock_Trans[v,v] += -0.25 * einsum('efmn,eb,afmn->ab', t2, f[v, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, b, m, n) * f(e, f) * t2(a, f, m, n)
    Fock_Trans[v,v] += 0.5 * einsum('ebmn,ef,afmn->ab', t2, f[v, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, b, m, n) * f(m, a) * t1(e, n)
    Fock_Trans[v,v] += 0.5 * einsum('ebmn,ma,en->ab', t2, f[o, v], t1, optimize=True)
    #   -(1.0/2.0) * t2(e, b, m, n) * f(m, e) * t1(a, n)
    Fock_Trans[v,v] += -0.5 * einsum('ebmn,me,an->ab', t2, f[o, v], t1, optimize=True)

    #   PH  ------------------------------------------------------------
    #   -1.0 * f1_OV(m, e) * t1(e, i) * t1(a, m)
    Fock_Trans[o,v] += -1.0 * einsum('me,ei,am->ia', f[o, v], t1, t1, optimize=True)
    #   (1.0/2.0) * t1(e, m) * f1_OO(n, i) * t2(a, e, m, n)
    Fock_Trans[o,v] += 0.5 * einsum('em,ni,aemn->ia', t1, f[o, o], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f1_VV(a, f) * t2(e, f, i, m)
    Fock_Trans[o,v] += -0.5 * einsum('em,af,efim->ia', t1, f[v, v], t2, optimize=True)
    #   -1.0 * t1(e, m) * f1_OO(n, m) * t2(a, e, i, n)
    Fock_Trans[o,v] += -1.0 * einsum('em,nm,aein->ia', t1, f[o, o], t2, optimize=True)
    #   1.0 * t1(e, m) * f1_VV(e, f) * t2(a, f, i, m)
    Fock_Trans[o,v] += 1.0 * einsum('em,ef,afim->ia', t1, f[v, v], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f1_OV(i, e) * t1(a, m)
    Fock_Trans[o,v] += -0.5 * einsum('em,ie,am->ia', t1, f[o, v], t1, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f1_OV(m, a) * t1(e, i)
    Fock_Trans[o,v] += -0.5 * einsum('em,ma,ei->ia', t1, f[o, v], t1, optimize=True)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_OV(i, e) * t2(a, f, m, n)
    Fock_Trans[o,v] += -0.25 * einsum('efmn,ie,afmn->ia', t2, f[o, v], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_OV(m, a) * t2(e, f, i, n)
    Fock_Trans[o,v] += -0.25 * einsum('efmn,ma,efin->ia', t2, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_OV(m, e) * t2(a, f, i, n)
    Fock_Trans[o,v] += 0.5 * einsum('efmn,me,afin->ia', t2, f[o, v], t2, optimize=True)

    #   HHHH -----------------------------------------------------------
    #   -(1.0/2.0) * t1(e, j) * f1_OV(i, f) * t2(e, f, k, l)
    V_Trans[o,o,o,o] += -(1.0/2.0) * einsum('ej,if,efkl->ijkl', t1, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t1(e, i) * f1_OV(j, f) * t2(e, f, k, l)
    V_Trans[o,o,o,o] += (1.0/2.0) * einsum('ei,jf,efkl->ijkl', t1, f[o, v], t2, optimize=True)
    #   (1.0/4.0) * t2(e, f, i, j) * f1_OO(m, k) * t2(e, f, l, m)
    V_Trans[o,o,o,o] += (1.0/4.0) * einsum('efij,mk,eflm->ijkl', t2, f[o, o], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, f, i, j) * f1_OO(m, l) * t2(e, f, k, m)
    V_Trans[o,o,o,o] += -(1.0/4.0) * einsum('efij,ml,efkm->ijkl', t2, f[o, o], t2, optimize=True)
    #   (1.0/4.0) * t2(e, f, m, i) * f1_OO(j, m) * t2(e, f, k, l)
    V_Trans[o,o,o,o] += (1.0/4.0) * einsum('efmi,jm,efkl->ijkl', t2, f[o, o], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, f, m, j) * f1_OO(i, m) * t2(e, f, k, l)
    V_Trans[o,o,o,o] += -(1.0/4.0) * einsum('efmj,im,efkl->ijkl', t2, f[o, o], t2, optimize=True)
    #   -1.0 * t2(e, f, i, j) * f1_VV(e, g) * t2(f, g, k, l)
    V_Trans[o,o,o,o] += -1.0 * einsum('efij,eg,fgkl->ijkl', t2, f[v, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, f, i, j) * f1_OV(k, e) * t1(f, l)
    V_Trans[o,o,o,o] += (1.0/2.0) * einsum('efij,ke,fl->ijkl', t2, f[o, v], t1, optimize=True)
    #   -(1.0/2.0) * t2(e, f, i, j) * f1_OV(l, e) * t1(f, k)
    V_Trans[o,o,o,o] += -(1.0/2.0) * einsum('efij,le,fk->ijkl', t2, f[o, v], t1, optimize=True)

    #   HHHP -----------------------------------------------------------
    #   (1.0/2.0) * t1(e, k) * f1_OO(m, j) * t2(a, e, i, m)
    V_Trans[o,o,o,v] += (1.0/2.0) * einsum('ek,mj,aeim->ijka', t1, f[o, o], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, k) * f1_VV(a, f) * t2(e, f, j, i)
    V_Trans[o,o,o,v] += -(1.0/2.0) * einsum('ek,af,efji->ijka', t1, f[v, v], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, k) * f1_OO(m, i) * t2(a, e, j, m)
    V_Trans[o,o,o,v] += -(1.0/2.0) * einsum('ek,mi,aejm->ijka', t1, f[o, o], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f1_OO(k, m) * t2(a, e, j, i)
    V_Trans[o,o,o,v] += -(1.0/2.0) * einsum('em,km,aeji->ijka', t1, f[o, o], t2, optimize=True)
    #   1.0 * t1(e, k) * f1_VV(e, f) * t2(a, f, j, i)
    V_Trans[o,o,o,v] += 1.0 * einsum('ek,ef,afji->ijka', t1, f[v, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, f, m, k) * f1_OV(j, e) * t2(a, f, i, m)
    V_Trans[o,o,o,v] += (1.0/2.0) * einsum('efmk,je,afim->ijka', t2, f[o, v], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, f, m, k) * f1_OV(m, a) * t2(e, f, j, i)
    V_Trans[o,o,o,v] += -(1.0/4.0) * einsum('efmk,ma,efji->ijka', t2, f[o, v], t2, optimize=True)
    #   -(1.0/2.0) * t2(e, f, m, k) * f1_OV(i, e) * t2(a, f, j, m)
    V_Trans[o,o,o,v] += -(1.0/2.0) * einsum('efmk,ie,afjm->ijka', t2, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, f, m, k) * f1_OV(m, e) * t2(a, f, j, i)
    V_Trans[o,o,o,v] += (1.0/2.0) * einsum('efmk,me,afji->ijka', t2, f[o, v], t2, optimize=True)

    #   HHPP -----------------------------------------------------------
    #   1.0 * f(m, e) * t1(e, i) * t2(a, b, j, m)
    V_Trans[o,o,v,v] += 1.0 * einsum('me,ei,abjm->ijab', f[o, v], t1, t2, optimize=True)
    #   1.0 * f(m, e) * t1(a, m) * t2(b, e, i, j)
    V_Trans[o,o,v,v] += 1.0 * einsum('me,am,beij->ijab', f[o, v], t1, t2, optimize=True)
    #   -1.0 * f(m, e) * t1(e, j) * t2(a, b, i, m)
    V_Trans[o,o,v,v] += -1.0 * einsum('me,ej,abim->ijab', f[o, v], t1, t2, optimize=True)
    #   -1.0 * f(m, e) * t1(b, m) * t2(a, e, i, j)
    V_Trans[o,o,v,v] += -1.0 * einsum('me,bm,aeij->ijab', f[o, v], t1, t2, optimize=True)
    #   (1.0/2.0) * t1(e, m) * f(i, e) * t2(a, b, j, m)
    V_Trans[o,o,v,v] += (1.0/2.0) * einsum('em,ie,abjm->ijab', t1, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t1(e, m) * f(m, a) * t2(b, e, i, j)
    V_Trans[o,o,v,v] += (1.0/2.0) * einsum('em,ma,beij->ijab', t1, f[o, v], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f(j, e) * t2(a, b, i, m)
    V_Trans[o,o,v,v] += -(1.0/2.0) * einsum('em,je,abim->ijab', t1, f[o, v], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f(m, b) * t2(a, e, i, j)
    V_Trans[o,o,v,v] += -(1.0/2.0) * einsum('em,mb,aeij->ijab', t1, f[o, v], t2, optimize=True)

    #   HPHP -----------------------------------------------------------
    #   (1.0/2.0) * t1(e, i) * f1_OV(m, b) * t2(a, e, j, m)
    V_Trans[o,v,o,v] += (1.0/2.0) * einsum('ei,mb,aejm->iajb', t1, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t1(b, m) * f1_OV(i, e) * t2(a, e, j, m)
    V_Trans[o,v,o,v] += (1.0/2.0) * einsum('bm,ie,aejm->iajb', t1, f[o, v], t2, optimize=True)
    #   -(1.0/2.0) * t2(e, b, m, i) * f1_OO(n, j) * t2(a, e, m, n)
    V_Trans[o,v,o,v] += -(1.0/2.0) * einsum('ebmi,nj,aemn->iajb', t2, f[o, o], t2, optimize=True)
    #   (1.0/2.0) * t2(e, b, m, i) * f1_VV(a, f) * t2(e, f, j, m)
    V_Trans[o,v,o,v] += (1.0/2.0) * einsum('ebmi,af,efjm->iajb', t2, f[v, v], t2, optimize=True)
    #   -(1.0/2.0) * t2(e, b, m, n) * f1_OO(i, m) * t2(a, e, j, n)
    V_Trans[o,v,o,v] += -(1.0/2.0) * einsum('ebmn,im,aejn->iajb', t2, f[o, o], t2, optimize=True)
    #   1.0 * t2(e, b, m, i) * f1_OO(n, m) * t2(a, e, j, n)
    V_Trans[o,v,o,v] += 1.0 * einsum('ebmi,nm,aejn->iajb', t2, f[o, o], t2, optimize=True)
    #   (1.0/2.0) * t2(e, f, m, i) * f1_VV(e, b) * t2(a, f, j, m)
    V_Trans[o,v,o,v] += (1.0/2.0) * einsum('efmi,eb,afjm->iajb', t2, f[v, v], t2, optimize=True)
    #   -1.0 * t2(e, b, m, i) * f1_VV(e, f) * t2(a, f, j, m)
    V_Trans[o,v,o,v] += -1.0 * einsum('ebmi,ef,afjm->iajb', t2, f[v, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, b, m, i) * f1_OV(j, e) * t1(a, m)
    V_Trans[o,v,o,v] += (1.0/2.0) * einsum('ebmi,je,am->iajb', t2, f[o, v], t1, optimize=True)
    #   (1.0/2.0) * t2(e, b, m, i) * f1_OV(m, a) * t1(e, j)
    V_Trans[o,v,o,v] += (1.0/2.0) * einsum('ebmi,ma,ej->iajb', t2, f[o, v], t1, optimize=True)

    #   HPPP -----------------------------------------------------------
    #   (1.0/2.0) * t1(a, m) * f1_VV(b, e) * t2(c, e, i, m)
    V_Trans[o,v,v,v] += (1.0/2.0) * einsum('am,be,ceim->iabc', t1, f[v, v], t2, optimize=True)
    #   -(1.0/2.0) * t1(a, m) * f1_OO(n, i) * t2(b, c, m, n)
    V_Trans[o,v,v,v] += -(1.0/2.0) * einsum('am,ni,bcmn->iabc', t1, f[o, o], t2, optimize=True)
    #   -(1.0/2.0) * t1(a, m) * f1_VV(c, e) * t2(b, e, i, m)
    V_Trans[o,v,v,v] += -(1.0/2.0) * einsum('am,ce,beim->iabc', t1, f[v, v], t2, optimize=True)
    #   1.0 * t1(a, m) * f1_OO(n, m) * t2(b, c, i, n)
    V_Trans[o,v,v,v] += 1.0 * einsum('am,nm,bcin->iabc', t1, f[o, o], t2, optimize=True)
    #   -(1.0/2.0) * t1(e, m) * f1_VV(e, a) * t2(b, c, i, m)
    V_Trans[o,v,v,v] += -(1.0/2.0) * einsum('em,ea,bcim->iabc', t1, f[v, v], t2, optimize=True)
    #   -(1.0/2.0) * t2(e, a, m, n) * f1_OV(m, b) * t2(c, e, i, n)
    V_Trans[o,v,v,v] += -(1.0/2.0) * einsum('eamn,mb,cein->iabc', t2, f[o, v], t2, optimize=True)
    #   (1.0/4.0) * t2(e, a, m, n) * f1_OV(i, e) * t2(b, c, m, n)
    V_Trans[o,v,v,v] += (1.0/4.0) * einsum('eamn,ie,bcmn->iabc', t2, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t2(e, a, m, n) * f1_OV(m, c) * t2(b, e, i, n)
    V_Trans[o,v,v,v] += (1.0/2.0) * einsum('eamn,mc,bein->iabc', t2, f[o, v], t2, optimize=True)
    #   -(1.0/2.0) * t2(e, a, m, n) * f1_OV(m, e) * t2(b, c, i, n)
    V_Trans[o,v,v,v] += -(1.0/2.0) * einsum('eamn,me,bcin->iabc', t2, f[o, v], t2, optimize=True)

    #   PPPP -----------------------------------------------------------
    #   -(1.0/2.0) * t1(d, m) * f1_OV(n, c) * t2(a, b, m, n)
    V_Trans[v,v,v,v] += -(1.0/2.0) * einsum('dm,nc,abmn->abcd', t1, f[o, v], t2, optimize=True)
    #   (1.0/2.0) * t1(c, m) * f1_OV(n, d) * t2(a, b, m, n)
    V_Trans[v,v,v,v] += (1.0/2.0) * einsum('cm,nd,abmn->abcd', t1, f[o, v], t2, optimize=True)
    #   -(1.0/4.0) * t2(c, d, m, n) * f1_VV(a, e) * t2(b, e, m, n)
    V_Trans[v,v,v,v] += -(1.0/4.0) * einsum('cdmn,ae,bemn->abcd', t2, f[v, v], t2, optimize=True)
    #   (1.0/4.0) * t2(c, d, m, n) * f1_VV(b, e) * t2(a, e, m, n)
    V_Trans[v,v,v,v] += (1.0/4.0) * einsum('cdmn,be,aemn->abcd', t2, f[v, v], t2, optimize=True)
    #   1.0 * t2(c, d, m, n) * f1_OO(o, m) * t2(a, b, n, o)
    V_Trans[v,v,v,v] += 1.0 * einsum('cdmn,om,abno->abcd', t2, f[o, o], t2, optimize=True)
    #   -(1.0/4.0) * t2(e, c, m, n) * f1_VV(e, d) * t2(a, b, m, n)
    V_Trans[v,v,v,v] += -(1.0/4.0) * einsum('ecmn,ed,abmn->abcd', t2, f[v, v], t2, optimize=True)
    #   (1.0/4.0) * t2(e, d, m, n) * f1_VV(e, c) * t2(a, b, m, n)
    V_Trans[v,v,v,v] += (1.0/4.0) * einsum('edmn,ec,abmn->abcd', t2, f[v, v], t2, optimize=True)
    #   (1.0/2.0) * t2(c, d, m, n) * f1_OV(m, a) * t1(b, n)
    V_Trans[v,v,v,v] += (1.0/2.0) * einsum('cdmn,ma,bn->abcd', t2, f[o, v], t1, optimize=True)
    #   -(1.0/2.0) * t2(c, d, m, n) * f1_OV(m, b) * t1(a, n)
    V_Trans[v,v,v,v] += -(1.0/2.0) * einsum('cdmn,mb,an->abcd', t2, f[o, v], t1, optimize=True)



# def V_2(Fock_Trans, V_Trans, t1, t2, f, g, o, v):

    #   HH  ------------------------------------------------------------
    #   -1.0 * v2ijab(m, i, e, f) * t1(e, j) * t1(f, m)
    #   -(1.0/4.0) * t1(e, i) * v2ijka(m, n, j, f) * t2(e, f, m, n)
    #   -(1.0/2.0) * t1(e, m) * v2ijka(n, i, j, f) * t2(e, f, m, n)
    #   1.0 * t1(e, m) * v2ijka(n, i, m, f) * t2(e, f, j, n)
    #   -(1.0/2.0) * t1(e, m) * v2iabc(i, e, g, f) * t2(f, g, j, m)
    #   (1.0/2.0) * t1(e, i) * v2iabc(m, e, g, f) * t2(f, g, j, m)
    #   1.0 * t1(e, m) * v2ijkl(n, i, j, m) * t1(e, n)
    #   1.0 * t1(e, m) * v2iajb(j, f, i, e) * t1(f, m)
    #   -1.0 * t1(e, i) * v2iajb(j, f, m, e) * t1(f, m)
    #   -1.0 * t1(e, m) * v2iajb(m, f, i, e) * t1(f, j)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2ijka(m, j, i, e) * t1(f, n)
    #   1.0 * t2(e, f, m, i) * v2ijka(m, j, n, e) * t1(f, n)
    #   -(1.0/2.0) * t2(e, f, m, i) * v2iabc(j, g, e, f) * t1(g, m)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijka(n, m, i, e) * t1(f, j)
    #   (1.0/2.0) * t2(e, f, m, i) * v2iabc(m, g, e, f) * t1(g, j)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2ijkl(o, i, j, m) * t2(e, f, n, o)
    #   -(1.0/4.0) * t2(e, f, m, i) * v2ijkl(n, o, j, m) * t2(e, f, n, o)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2iajb(j, g, i, e) * t2(f, g, m, n)
    #   1.0 * t2(e, f, m, i) * v2iajb(j, g, n, e) * t2(f, g, m, n)
    #   1.0 * t2(e, f, m, n) * v2iajb(m, g, i, e) * t2(f, g, j, n)
    #   -1.0 * t2(e, f, m, i) * v2iajb(m, g, n, e) * t2(f, g, j, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijkl(o, i, m, n) * t2(e, f, j, o)
    #   -(1.0/4.0) * t2(e, f, m, i) * v2abcd(e, f, g, h) * t2(g, h, j, m)
    #   -1.0 * t1(e, m) * t1(f, i) * v2ijab(j, m, e, f)

    #   PP  ------------------------------------------------------------
    #   1.0 * v2ijab(m, n, e, b) * t1(a, m) * t1(e, n)
    #   -(1.0/4.0) * t1(b, m) * v2iabc(n, a, f, e) * t2(e, f, m, n)
    #   -(1.0/2.0) * t1(e, m) * v2iabc(n, a, b, f) * t2(e, f, m, n)
    #   -(1.0/2.0) * t1(e, m) * v2ijka(n, o, m, b) * t2(a, e, n, o)
    #   (1.0/2.0) * t1(b, m) * v2ijka(n, o, m, e) * t2(a, e, n, o)
    #   1.0 * t1(e, m) * v2iabc(n, e, b, f) * t2(a, f, m, n)
    #   -1.0 * t1(e, m) * v2iajb(m, b, n, a) * t1(e, n)
    #   1.0 * t1(b, m) * v2iajb(m, e, n, a) * t1(e, n)
    #   -1.0 * t1(e, m) * v2abcd(a, e, f, b) * t1(f, m)
    #   1.0 * t1(e, m) * v2iajb(m, b, n, e) * t1(a, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2iabc(m, b, a, e) * t1(f, n)
    #   1.0 * t2(e, b, m, n) * v2iabc(m, f, a, e) * t1(f, n)
    #   -(1.0/2.0) * t2(e, b, m, n) * v2ijka(n, m, o, a) * t1(e, o)
    #   (1.0/2.0) * t2(e, b, m, n) * v2ijka(n, m, o, e) * t1(a, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2iabc(m, b, e, f) * t1(a, n)
    #   (1.0/2.0) * t2(e, f, m, n) * v2iajb(m, b, o, a) * t2(e, f, n, o)
    #   -1.0 * t2(e, b, m, n) * v2iajb(m, f, o, a) * t2(e, f, n, o)
    #   (1.0/2.0) * t2(e, f, m, n) * v2abcd(a, e, g, b) * t2(f, g, m, n)
    #   (1.0/4.0) * t2(e, b, m, n) * v2abcd(a, e, f, g) * t2(f, g, m, n)
    #   -1.0 * t2(e, f, m, n) * v2iajb(m, b, o, e) * t2(a, f, n, o)
    #   1.0 * t2(e, b, m, n) * v2iajb(m, f, o, e) * t2(a, f, n, o)
    #   (1.0/4.0) * t2(e, b, m, n) * v2ijkl(o, p, m, n) * t2(a, e, o, p)
    #   (1.0/4.0) * t2(e, f, m, n) * v2abcd(e, f, g, b) * t2(a, g, m, n)
    #   1.0 * t1(e, m) * t1(b, n) * v2ijab(m, n, a, e)

    #   PH  ------------------------------------------------------------
    #   -1.0 * v2ijka(m, n, i, e) * t1(a, m) * t1(e, n)
    #   1.0 * v2iabc(m, a, f, e) * t1(e, i) * t1(f, m)
    #   -(1.0/2.0) * v2ijab(m, n, e, f) * t1(e, i) * t2(a, f, m, n)
    #   -(1.0/2.0) * v2ijab(m, n, e, f) * t1(a, m) * t2(e, f, i, n)
    #   1.0 * v2ijab(m, n, e, f) * t1(e, m) * t2(a, f, i, n)
    #   -(1.0/2.0) * t1(e, m) * v2iajb(i, f, n, a) * t2(e, f, m, n)
    #   (1.0/2.0) * t1(e, m) * v2ijkl(n, o, i, m) * t2(a, e, n, o)
    #   1.0 * t1(e, m) * v2iajb(i, f, n, e) * t2(a, f, m, n)
    #   1.0 * t1(e, m) * v2iajb(m, f, n, a) * t2(e, f, i, n)
    #   (1.0/2.0) * t1(e, m) * v2abcd(a, e, f, g) * t2(f, g, i, m)
    #   -1.0 * t1(e, m) * v2iajb(m, f, n, e) * t2(a, f, i, n)
    #   -1.0 * t1(e, m) * v2ijka(m, i, n, a) * t1(e, n)
    #   1.0 * t1(e, m) * v2iabc(i, f, a, e) * t1(f, m)
    #   1.0 * t1(e, m) * v2ijka(m, i, n, e) * t1(a, n)
    #   -1.0 * t1(e, m) * v2iabc(m, f, a, e) * t1(f, i)
    #   (1.0/2.0) * t2(e, f, m, n) * v2ijab(i, m, a, e) * t1(f, n)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijab(i, m, e, f) * t1(a, n)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijab(m, n, a, e) * t1(f, i)
    #   (1.0/2.0) * t2(e, f, m, n) * v2ijka(m, i, o, a) * t2(e, f, n, o)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2iabc(i, g, a, e) * t2(f, g, m, n)
    #   -1.0 * t2(e, f, m, n) * v2ijka(m, i, o, e) * t2(a, f, n, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2iabc(i, g, e, f) * t2(a, g, m, n)
    #   1.0 * t2(e, f, m, n) * v2iabc(m, g, a, e) * t2(f, g, i, n)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijka(n, m, o, a) * t2(e, f, i, o)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2ijka(n, m, o, e) * t2(a, f, i, o)
    #   (1.0/2.0) * t2(e, f, m, n) * v2iabc(m, g, e, f) * t2(a, g, i, n)

    #   HHHH -----------------------------------------------------------
    #   1.0 * v2ijab(i, j, e, f) * t1(e, k) * t1(f, l)
    #   (1.0/2.0) * t1(e, j) * v2ijkl(m, i, k, l) * t1(e, m)
    #   -(1.0/2.0) * t1(e, i) * v2ijkl(m, j, k, l) * t1(e, m)
    #   -(1.0/2.0) * t1(e, m) * v2ijkl(i, j, k, m) * t1(e, l)
    #   -1.0 * t1(e, i) * v2iajb(k, f, j, e) * t1(f, l)
    #   1.0 * t1(e, j) * v2iajb(k, f, i, e) * t1(f, l)
    #   (1.0/2.0) * t1(e, m) * v2ijkl(i, j, l, m) * t1(e, k)
    #   1.0 * t1(e, i) * v2iajb(l, f, j, e) * t1(f, k)
    #   -1.0 * t1(e, j) * v2iajb(l, f, i, e) * t1(f, k)
    #   -(1.0/2.0) * t1(e, j) * v2ijka(m, i, k, f) * t2(e, f, l, m)
    #   (1.0/2.0) * t1(e, i) * v2ijka(m, j, k, f) * t2(e, f, l, m)
    #   -(1.0/2.0) * t1(e, m) * v2ijka(i, j, k, f) * t2(e, f, l, m)
    #   (1.0/2.0) * t1(e, j) * v2ijka(m, i, l, f) * t2(e, f, k, m)
    #   -(1.0/2.0) * t1(e, i) * v2ijka(m, j, l, f) * t2(e, f, k, m)
    #   (1.0/2.0) * t1(e, m) * v2ijka(i, j, l, f) * t2(e, f, k, m)
    #   -1.0 * t1(e, m) * v2ijka(i, j, m, f) * t2(e, f, k, l)
    #   (1.0/2.0) * t1(e, i) * v2iabc(j, e, g, f) * t2(f, g, k, l)
    #   -(1.0/2.0) * t1(e, j) * v2iabc(i, e, g, f) * t2(f, g, k, l)
    #   (1.0/8.0) * t2(e, f, i, j) * v2ijkl(m, n, k, l) * t2(e, f, m, n)
    #   (1.0/4.0) * t2(e, f, m, j) * v2ijkl(n, i, k, l) * t2(e, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, i) * v2ijkl(n, j, k, l) * t2(e, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijkl(i, j, k, m) * t2(e, f, l, n)
    #   (1.0/2.0) * t2(e, f, m, i) * v2ijkl(n, j, k, m) * t2(e, f, l, n)
    #   -(1.0/2.0) * t2(e, f, m, j) * v2ijkl(n, i, k, m) * t2(e, f, l, n)
    #   -1.0 * t2(e, f, m, i) * v2iajb(k, g, j, e) * t2(f, g, l, m)
    #   1.0 * t2(e, f, m, j) * v2iajb(k, g, i, e) * t2(f, g, l, m)
    #   -1.0 * t2(e, f, i, j) * v2iajb(k, g, m, e) * t2(f, g, l, m)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijkl(i, j, l, m) * t2(e, f, k, n)
    #   -(1.0/2.0) * t2(e, f, m, i) * v2ijkl(n, j, l, m) * t2(e, f, k, n)
    #   (1.0/2.0) * t2(e, f, m, j) * v2ijkl(n, i, l, m) * t2(e, f, k, n)
    #   1.0 * t2(e, f, m, i) * v2iajb(l, g, j, e) * t2(f, g, k, m)
    #   -1.0 * t2(e, f, m, j) * v2iajb(l, g, i, e) * t2(f, g, k, m)
    #   1.0 * t2(e, f, i, j) * v2iajb(l, g, m, e) * t2(f, g, k, m)
    #   -1.0 * t2(e, f, m, i) * v2iajb(m, g, j, e) * t2(f, g, k, l)
    #   1.0 * t2(e, f, m, j) * v2iajb(m, g, i, e) * t2(f, g, k, l)
    #   (1.0/8.0) * t2(e, f, m, n) * v2ijkl(i, j, m, n) * t2(e, f, k, l)
    #   (1.0/4.0) * t2(e, f, i, j) * v2abcd(e, f, g, h) * t2(g, h, k, l)
    #   -(1.0/2.0) * t2(e, f, m, i) * v2ijka(l, k, j, e) * t1(f, m)
    #   (1.0/2.0) * t2(e, f, m, j) * v2ijka(l, k, i, e) * t1(f, m)
    #   -1.0 * t2(e, f, i, j) * v2ijka(l, k, m, e) * t1(f, m)
    #   (1.0/2.0) * t2(e, f, m, i) * v2ijka(m, k, j, e) * t1(f, l)
    #   -(1.0/2.0) * t2(e, f, m, j) * v2ijka(m, k, i, e) * t1(f, l)
    #   (1.0/2.0) * t2(e, f, i, j) * v2iabc(k, g, e, f) * t1(g, l)
    #   -(1.0/2.0) * t2(e, f, m, i) * v2ijka(m, l, j, e) * t1(f, k)
    #   (1.0/2.0) * t2(e, f, m, j) * v2ijka(m, l, i, e) * t1(f, k)
    #   -(1.0/2.0) * t2(e, f, i, j) * v2iabc(l, g, e, f) * t1(g, k)
    #   1.0 * t1(e, i) * t1(f, j) * v2ijab(k, l, e, f)

    #   HHHP -----------------------------------------------------------
    #   -1.0 * v2ijka(m, k, j, e) * t1(a, m) * t1(e, i)
    #   -1.0 * v2ijka(m, k, j, e) * t1(a, m) * t1(e, i)
    #   1.0 * v2iabc(k, a, f, e) * t1(e, j) * t1(f, i)
    #   1.0 * v2ijka(m, k, i, e) * t1(e, j) * t1(a, m)
    #   1.0 * v2ijab(m, k, e, f) * t1(e, j) * t2(a, f, i, m)
    #   -(1.0/2.0) * v2ijab(m, k, e, f) * t1(a, m) * t2(e, f, j, i)
    #   -1.0 * v2ijab(m, k, e, f) * t1(e, i) * t2(a, f, j, m)
    #   1.0 * v2ijab(m, k, e, f) * t1(e, m) * t2(a, f, j, i)
    #   -(1.0/2.0) * t1(e, k) * v2ijka(i, j, m, a) * t1(e, m)
    #   -(1.0/2.0) * t1(e, m) * v2ijka(m, j, k, a) * t1(e, i)
    #   1.0 * t1(e, k) * v2iabc(j, f, a, e) * t1(f, i)
    #   -(1.0/2.0) * t1(e, m) * v2ijka(i, j, k, e) * t1(a, m)
    #   1.0 * t1(e, k) * v2ijka(i, j, m, e) * t1(a, m)
    #   (1.0/2.0) * t1(e, m) * v2ijka(m, i, k, a) * t1(e, j)
    #   -1.0 * t1(e, k) * v2iabc(i, f, a, e) * t1(f, j)
    #   -(1.0/2.0) * t1(e, k) * v2iajb(m, a, j, f) * t2(e, f, i, m)
    #   (1.0/2.0) * t1(e, m) * v2iajb(k, a, j, f) * t2(e, f, i, m)
    #   (1.0/4.0) * t1(e, k) * v2ijkl(m, n, j, i) * t2(a, e, m, n)
    #   (1.0/2.0) * t1(e, m) * v2ijkl(n, k, j, i) * t2(a, e, m, n)
    #   (1.0/2.0) * t1(e, k) * v2iajb(m, a, i, f) * t2(e, f, j, m)
    #   -(1.0/2.0) * t1(e, m) * v2iajb(k, a, i, f) * t2(e, f, j, m)
    #   -1.0 * t1(e, m) * v2ijkl(n, k, j, m) * t2(a, e, i, n)
    #   -1.0 * t1(e, m) * v2iajb(k, e, j, f) * t2(a, f, i, m)
    #   1.0 * t1(e, k) * v2iajb(m, e, j, f) * t2(a, f, i, m)
    #   1.0 * t1(e, m) * v2iajb(k, a, m, f) * t2(e, f, j, i)
    #   (1.0/2.0) * t1(e, k) * v2abcd(a, e, f, g) * t2(f, g, j, i)
    #   1.0 * t1(e, m) * v2ijkl(n, k, i, m) * t2(a, e, j, n)
    #   1.0 * t1(e, m) * v2iajb(k, e, i, f) * t2(a, f, j, m)
    #   -1.0 * t1(e, k) * v2iajb(m, e, i, f) * t2(a, f, j, m)
    #   -1.0 * t1(e, m) * v2iajb(k, e, m, f) * t2(a, f, j, i)
    #   -(1.0/4.0) * t2(e, f, m, k) * v2ijka(i, j, n, a) * t2(e, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijka(m, j, k, a) * t2(e, f, i, n)
    #   (1.0/2.0) * t2(e, f, m, k) * v2ijka(m, j, n, a) * t2(e, f, i, n)
    #   1.0 * t2(e, f, m, k) * v2iabc(j, g, a, e) * t2(f, g, i, m)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijka(i, j, k, e) * t2(a, f, m, n)
    #   1.0 * t2(e, f, m, k) * v2ijka(i, j, n, e) * t2(a, f, m, n)
    #   (1.0/2.0) * t2(e, f, m, n) * v2ijka(m, j, k, e) * t2(a, f, i, n)
    #   -1.0 * t2(e, f, m, k) * v2ijka(m, j, n, e) * t2(a, f, i, n)
    #   (1.0/2.0) * t2(e, f, m, k) * v2iabc(j, g, e, f) * t2(a, g, i, m)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijka(m, i, k, a) * t2(e, f, j, n)
    #   -(1.0/2.0) * t2(e, f, m, k) * v2ijka(m, i, n, a) * t2(e, f, j, n)
    #   -1.0 * t2(e, f, m, k) * v2iabc(i, g, a, e) * t2(f, g, j, m)
    #   1.0 * t2(e, f, m, k) * v2iabc(m, g, a, e) * t2(f, g, j, i)
    #   (1.0/8.0) * t2(e, f, m, n) * v2ijka(n, m, k, a) * t2(e, f, j, i)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2ijka(m, i, k, e) * t2(a, f, j, n)
    #   1.0 * t2(e, f, m, k) * v2ijka(m, i, n, e) * t2(a, f, j, n)
    #   -(1.0/2.0) * t2(e, f, m, k) * v2iabc(i, g, e, f) * t2(a, g, j, m)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijka(n, m, k, e) * t2(a, f, j, i)
    #   (1.0/2.0) * t2(e, f, m, k) * v2iabc(m, g, e, f) * t2(a, g, j, i)
    #   -(1.0/2.0) * t2(e, f, m, k) * v2ijab(j, i, a, e) * t1(f, m)
    #   (1.0/2.0) * t2(e, f, m, k) * v2ijab(j, m, a, e) * t1(f, i)
    #   -(1.0/4.0) * t2(e, f, m, k) * v2ijab(j, i, e, f) * t1(a, m)
    #   -(1.0/2.0) * t2(e, f, m, k) * v2ijab(i, m, a, e) * t1(f, j)

    #   HHPP -----------------------------------------------------------
    #   1.0 * v2iajb(i, e, m, a) * t1(e, j) * t1(b, m)
    #   1.0 * v2ijkl(m, n, i, j) * t1(a, m) * t1(b, n)
    #   -1.0 * v2iajb(i, e, m, b) * t1(a, m) * t1(e, j)
    #   -1.0 * v2iajb(j, e, m, a) * t1(e, i) * t1(b, m)
    #   1.0 * v2abcd(a, b, e, f) * t1(e, i) * t1(f, j)
    #   1.0 * v2iajb(j, e, m, b) * t1(e, i) * t1(a, m)
    #   -1.0 * v2ijka(m, n, i, e) * t1(a, m) * t2(b, e, j, n)
    #   (1.0/2.0) * v2ijka(m, n, i, e) * t1(e, j) * t2(a, b, m, n)
    #   1.0 * v2ijka(m, n, i, e) * t1(b, m) * t2(a, e, j, n)
    #   -1.0 * v2ijka(m, n, i, e) * t1(e, m) * t2(a, b, j, n)
    #   1.0 * v2iabc(m, a, f, e) * t1(e, i) * t2(b, f, j, m)
    #   -(1.0/2.0) * v2ijka(m, n, j, e) * t1(e, i) * t2(a, b, m, n)
    #   -1.0 * v2iabc(m, b, f, e) * t1(e, i) * t2(a, f, j, m)
    #   -1.0 * v2iabc(m, a, f, e) * t1(e, j) * t2(b, f, i, m)
    #   -(1.0/2.0) * v2iabc(m, a, f, e) * t1(b, m) * t2(e, f, i, j)
    #   1.0 * v2iabc(m, a, f, e) * t1(e, m) * t2(b, f, i, j)
    #   1.0 * v2ijka(m, n, j, e) * t1(a, m) * t2(b, e, i, n)
    #   (1.0/2.0) * v2iabc(m, b, f, e) * t1(a, m) * t2(e, f, i, j)
    #   -1.0 * v2ijka(m, n, j, e) * t1(b, m) * t2(a, e, i, n)
    #   1.0 * v2ijka(m, n, j, e) * t1(e, m) * t2(a, b, i, n)
    #   1.0 * v2iabc(m, b, f, e) * t1(e, j) * t2(a, f, i, m)
    #   -1.0 * v2iabc(m, b, f, e) * t1(e, m) * t2(a, f, i, j)
    #   (1.0/2.0) * t1(e, m) * v2ijka(j, i, n, a) * t2(b, e, m, n)
    #   -(1.0/2.0) * t1(e, m) * v2iabc(i, f, a, b) * t2(e, f, j, m)
    #   -(1.0/2.0) * t1(e, m) * v2ijka(j, i, n, b) * t2(a, e, m, n)
    #   (1.0/2.0) * t1(e, m) * v2iabc(j, f, a, b) * t2(e, f, i, m)
    #   -1.0 * t1(e, m) * v2ijka(m, i, n, a) * t2(b, e, j, n)
    #   1.0 * t1(e, m) * v2iabc(i, f, a, e) * t2(b, f, j, m)
    #   1.0 * t1(e, m) * v2ijka(j, i, n, e) * t2(a, b, m, n)
    #   1.0 * t1(e, m) * v2ijka(m, i, n, b) * t2(a, e, j, n)
    #   -1.0 * t1(e, m) * v2iabc(i, f, b, e) * t2(a, f, j, m)
    #   -1.0 * t1(e, m) * v2ijka(m, i, n, e) * t2(a, b, j, n)
    #   1.0 * t1(e, m) * v2ijka(m, j, n, a) * t2(b, e, i, n)
    #   -1.0 * t1(e, m) * v2iabc(j, f, a, e) * t2(b, f, i, m)
    #   -1.0 * t1(e, m) * v2iabc(m, f, a, b) * t2(e, f, i, j)
    #   1.0 * t1(e, m) * v2iabc(m, f, a, e) * t2(b, f, i, j)
    #   -1.0 * t1(e, m) * v2ijka(m, j, n, b) * t2(a, e, i, n)
    #   1.0 * t1(e, m) * v2iabc(j, f, b, e) * t2(a, f, i, m)
    #   1.0 * t1(e, m) * v2ijka(m, j, n, e) * t2(a, b, i, n)
    #   -1.0 * t1(e, m) * v2iabc(m, f, b, e) * t2(a, f, i, j)
    #   -(1.0/2.0) * v2ijab(m, n, e, f) * t2(a, e, i, j) * t2(b, f, m, n)
    #   -(1.0/2.0) * v2ijab(m, n, e, f) * t2(a, b, i, m) * t2(e, f, j, n)
    #   1.0 * v2ijab(m, n, e, f) * t2(a, e, i, m) * t2(b, f, j, n)
    #   (1.0/2.0) * v2ijab(m, n, e, f) * t2(b, e, i, j) * t2(a, f, m, n)
    #   (1.0/4.0) * v2ijab(m, n, e, f) * t2(e, f, i, j) * t2(a, b, m, n)
    #   -1.0 * v2ijab(m, n, e, f) * t2(b, e, i, m) * t2(a, f, j, n)
    #   -(1.0/2.0) * v2ijab(m, n, e, f) * t2(e, f, i, m) * t2(a, b, j, n)
    #   -(1.0/2.0) * t1(e, m) * v2ijab(i, j, a, e) * t1(b, m)
    #   -(1.0/2.0) * t1(e, m) * v2ijab(i, m, a, b) * t1(e, j)
    #   (1.0/2.0) * t1(e, m) * v2ijab(i, j, b, e) * t1(a, m)
    #   (1.0/2.0) * t1(e, m) * v2ijab(j, m, a, b) * t1(e, i)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijab(i, j, a, e) * t2(b, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijab(i, m, a, b) * t2(e, f, j, n)
    #   (1.0/2.0) * t2(e, f, m, n) * v2ijab(i, m, a, e) * t2(b, f, j, n)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijab(i, j, b, e) * t2(a, f, m, n)
    #   (1.0/8.0) * t2(e, f, m, n) * v2ijab(i, j, e, f) * t2(a, b, m, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2ijab(i, m, b, e) * t2(a, f, j, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijab(i, m, e, f) * t2(a, b, j, n)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijab(j, m, a, b) * t2(e, f, i, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2ijab(j, m, a, e) * t2(b, f, i, n)
    #   (1.0/8.0) * t2(e, f, m, n) * v2ijab(m, n, a, b) * t2(e, f, i, j)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2ijab(m, n, a, e) * t2(b, f, i, j)
    #   (1.0/2.0) * t2(e, f, m, n) * v2ijab(j, m, b, e) * t2(a, f, i, n)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijab(j, m, e, f) * t2(a, b, i, n)
    #   (1.0/4.0) * t2(e, f, m, n) * v2ijab(m, n, b, e) * t2(a, f, i, j)

    #   HPHP -----------------------------------------------------------
    #   1.0 * v2ijab(m, i, e, b) * t1(e, j) * t1(a, m)
    #   -(1.0/2.0) * t1(e, i) * v2iajb(m, a, j, b) * t1(e, m)
    #   -(1.0/2.0) * t1(b, m) * v2iajb(i, a, j, e) * t1(e, m)
    #   -1.0 * t1(b, m) * v2ijkl(n, i, j, m) * t1(a, n)
    #   -(1.0/2.0) * t1(e, m) * v2iajb(i, e, j, b) * t1(a, m)
    #   1.0 * t1(e, i) * v2iajb(m, e, j, b) * t1(a, m)
    #   -(1.0/2.0) * t1(e, m) * v2iajb(i, a, m, b) * t1(e, j)
    #   1.0 * t1(b, m) * v2iajb(i, a, m, e) * t1(e, j)
    #   -1.0 * t1(e, i) * v2abcd(a, e, f, b) * t1(f, j)
    #   -(1.0/4.0) * t1(e, i) * v2ijka(m, n, j, b) * t2(a, e, m, n)
    #   (1.0/2.0) * t1(b, m) * v2ijka(n, i, j, e) * t2(a, e, m, n)
    #   -(1.0/2.0) * t1(e, m) * v2ijka(n, i, j, b) * t2(a, e, m, n)
    #   -(1.0/2.0) * t1(e, i) * v2iabc(m, a, b, f) * t2(e, f, j, m)
    #   (1.0/4.0) * t1(b, m) * v2iabc(i, a, f, e) * t2(e, f, j, m)
    #   (1.0/2.0) * t1(e, m) * v2iabc(i, a, b, f) * t2(e, f, j, m)
    #   1.0 * t1(e, m) * v2ijka(n, i, m, b) * t2(a, e, j, n)
    #   -1.0 * t1(b, m) * v2ijka(n, i, m, e) * t2(a, e, j, n)
    #   -1.0 * t1(e, m) * v2iabc(i, e, b, f) * t2(a, f, j, m)
    #   1.0 * t1(e, i) * v2iabc(m, e, b, f) * t2(a, f, j, m)
    #   (1.0/2.0) * t2(e, b, m, i) * v2iajb(n, a, j, f) * t2(e, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, i) * v2iajb(n, a, j, b) * t2(e, f, m, n)
    #   -(1.0/4.0) * t2(e, b, m, n) * v2iajb(i, a, j, f) * t2(e, f, m, n)
    #   -1.0 * t2(e, b, m, n) * v2ijkl(o, i, j, m) * t2(a, e, n, o)
    #   -(1.0/2.0) * t2(e, b, m, i) * v2ijkl(n, o, j, m) * t2(a, e, n, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2iajb(i, e, j, b) * t2(a, f, m, n)
    #   (1.0/2.0) * t2(e, b, m, n) * v2iajb(i, e, j, f) * t2(a, f, m, n)
    #   1.0 * t2(e, f, m, i) * v2iajb(n, e, j, b) * t2(a, f, m, n)
    #   -1.0 * t2(e, b, m, i) * v2iajb(n, e, j, f) * t2(a, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2iajb(i, a, m, b) * t2(e, f, j, n)
    #   1.0 * t2(e, b, m, n) * v2iajb(i, a, m, f) * t2(e, f, j, n)
    #   (1.0/2.0) * t2(e, f, m, i) * v2iajb(n, a, m, b) * t2(e, f, j, n)
    #   -1.0 * t2(e, b, m, i) * v2iajb(n, a, m, f) * t2(e, f, j, n)
    #   -1.0 * t2(e, f, m, i) * v2abcd(a, e, g, b) * t2(f, g, j, m)
    #   -(1.0/2.0) * t2(e, b, m, i) * v2abcd(a, e, f, g) * t2(f, g, j, m)
    #   (1.0/2.0) * t2(e, f, m, n) * v2iajb(i, e, m, b) * t2(a, f, j, n)
    #   -1.0 * t2(e, b, m, n) * v2iajb(i, e, m, f) * t2(a, f, j, n)
    #   -1.0 * t2(e, f, m, i) * v2iajb(n, e, m, b) * t2(a, f, j, n)
    #   1.0 * t2(e, b, m, i) * v2iajb(n, e, m, f) * t2(a, f, j, n)
    #   -(1.0/2.0) * t2(e, b, m, n) * v2ijkl(o, i, m, n) * t2(a, e, j, o)
    #   -(1.0/2.0) * t2(e, f, m, i) * v2abcd(e, f, g, b) * t2(a, g, j, m)
    #   -(1.0/2.0) * t2(e, b, m, n) * v2ijka(m, j, i, a) * t1(e, n)
    #   1.0 * t2(e, b, m, i) * v2ijka(m, j, n, a) * t1(e, n)
    #   (1.0/2.0) * t2(e, f, m, i) * v2iabc(j, b, a, e) * t1(f, m)
    #   -1.0 * t2(e, b, m, i) * v2iabc(j, f, a, e) * t1(f, m)
    #   (1.0/2.0) * t2(e, b, m, n) * v2ijka(m, j, i, e) * t1(a, n)
    #   -1.0 * t2(e, b, m, i) * v2ijka(m, j, n, e) * t1(a, n)
    #   (1.0/4.0) * t2(e, f, m, i) * v2iabc(j, b, e, f) * t1(a, m)
    #   -(1.0/2.0) * t2(e, f, m, i) * v2iabc(m, b, a, e) * t1(f, j)
    #   1.0 * t2(e, b, m, i) * v2iabc(m, f, a, e) * t1(f, j)
    #   -(1.0/4.0) * t2(e, b, m, n) * v2ijka(n, m, i, a) * t1(e, j)
    #   1.0 * t1(b, m) * t1(e, i) * v2ijab(j, m, a, e)

    #   HPPP -----------------------------------------------------------
    #   -1.0 * v2iabc(m, b, a, e) * t1(e, i) * t1(c, m)
    #   1.0 * v2ijka(m, n, i, a) * t1(b, m) * t1(c, n)
    #   1.0 * v2iabc(m, c, a, e) * t1(b, m) * t1(e, i)
    #   -1.0 * v2ijab(m, n, e, a) * t1(b, m) * t2(c, e, i, n)
    #   (1.0/2.0) * v2ijab(m, n, e, a) * t1(e, i) * t2(b, c, m, n)
    #   1.0 * v2ijab(m, n, e, a) * t1(c, m) * t2(b, e, i, n)
    #   -1.0 * v2ijab(m, n, e, a) * t1(e, m) * t2(b, c, i, n)
    #   -(1.0/2.0) * t1(a, m) * v2iabc(i, e, b, c) * t1(e, m)
    #   1.0 * t1(a, m) * v2ijka(m, i, n, b) * t1(c, n)
    #   -(1.0/2.0) * t1(e, m) * v2iabc(i, a, b, e) * t1(c, m)
    #   -(1.0/2.0) * t1(e, m) * v2iabc(m, a, b, c) * t1(e, i)
    #   1.0 * t1(a, m) * v2iabc(m, e, b, c) * t1(e, i)
    #   -1.0 * t1(a, m) * v2ijka(m, i, n, c) * t1(b, n)
    #   (1.0/2.0) * t1(e, m) * v2iabc(i, a, c, e) * t1(b, m)
    #   (1.0/2.0) * t1(a, m) * v2iajb(n, b, i, e) * t2(c, e, m, n)
    #   -(1.0/2.0) * t1(e, m) * v2iajb(n, b, i, a) * t2(c, e, m, n)
    #   -(1.0/4.0) * t1(a, m) * v2abcd(b, c, e, f) * t2(e, f, i, m)
    #   -(1.0/2.0) * t1(e, m) * v2abcd(b, c, f, a) * t2(e, f, i, m)
    #   -(1.0/2.0) * t1(a, m) * v2iajb(n, c, i, e) * t2(b, e, m, n)
    #   (1.0/2.0) * t1(e, m) * v2iajb(n, c, i, a) * t2(b, e, m, n)
    #   1.0 * t1(e, m) * v2iajb(n, b, m, a) * t2(c, e, i, n)
    #   -1.0 * t1(a, m) * v2iajb(n, b, m, e) * t2(c, e, i, n)
    #   1.0 * t1(e, m) * v2abcd(b, e, f, a) * t2(c, f, i, m)
    #   -(1.0/2.0) * t1(a, m) * v2ijkl(n, o, i, m) * t2(b, c, n, o)
    #   -1.0 * t1(e, m) * v2iajb(n, e, i, a) * t2(b, c, m, n)
    #   -1.0 * t1(e, m) * v2iajb(n, c, m, a) * t2(b, e, i, n)
    #   1.0 * t1(a, m) * v2iajb(n, c, m, e) * t2(b, e, i, n)
    #   -1.0 * t1(e, m) * v2abcd(c, e, f, a) * t2(b, f, i, m)
    #   1.0 * t1(e, m) * v2iajb(n, e, m, a) * t2(b, c, i, n)
    #   -(1.0/4.0) * t2(e, a, m, n) * v2iabc(i, f, b, c) * t2(e, f, m, n)
    #   1.0 * t2(e, a, m, n) * v2ijka(m, i, o, b) * t2(c, e, n, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2iabc(i, a, b, e) * t2(c, f, m, n)
    #   (1.0/2.0) * t2(e, a, m, n) * v2iabc(i, f, b, e) * t2(c, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2iabc(m, a, b, c) * t2(e, f, i, n)
    #   1.0 * t2(e, a, m, n) * v2iabc(m, f, b, c) * t2(e, f, i, n)
    #   (1.0/2.0) * t2(e, f, m, n) * v2iabc(m, a, b, e) * t2(c, f, i, n)
    #   -1.0 * t2(e, a, m, n) * v2iabc(m, f, b, e) * t2(c, f, i, n)
    #   (1.0/2.0) * t2(e, a, m, n) * v2ijka(n, m, o, b) * t2(c, e, i, o)
    #   -1.0 * t2(e, a, m, n) * v2ijka(m, i, o, c) * t2(b, e, n, o)
    #   (1.0/4.0) * t2(e, f, m, n) * v2iabc(i, a, c, e) * t2(b, f, m, n)
    #   -(1.0/2.0) * t2(e, a, m, n) * v2iabc(i, f, c, e) * t2(b, f, m, n)
    #   1.0 * t2(e, a, m, n) * v2ijka(m, i, o, e) * t2(b, c, n, o)
    #   (1.0/8.0) * t2(e, f, m, n) * v2iabc(i, a, e, f) * t2(b, c, m, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * v2iabc(m, a, c, e) * t2(b, f, i, n)
    #   1.0 * t2(e, a, m, n) * v2iabc(m, f, c, e) * t2(b, f, i, n)
    #   -(1.0/2.0) * t2(e, a, m, n) * v2ijka(n, m, o, c) * t2(b, e, i, o)
    #   (1.0/2.0) * t2(e, a, m, n) * v2ijka(n, m, o, e) * t2(b, c, i, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2iabc(m, a, e, f) * t2(b, c, i, n)
    #   (1.0/2.0) * t2(e, a, m, n) * v2ijab(i, m, b, c) * t1(e, n)
    #   -(1.0/2.0) * t2(e, a, m, n) * v2ijab(i, m, b, e) * t1(c, n)
    #   (1.0/4.0) * t2(e, a, m, n) * v2ijab(m, n, b, c) * t1(e, i)
    #   (1.0/2.0) * t2(e, a, m, n) * v2ijab(i, m, c, e) * t1(b, n)

    #   PPPP -----------------------------------------------------------
    #   1.0 * v2ijab(m, n, c, d) * t1(a, m) * t1(b, n)
    #   (1.0/2.0) * t1(d, m) * v2abcd(a, b, e, c) * t1(e, m)
    #   -(1.0/2.0) * t1(c, m) * v2abcd(a, b, e, d) * t1(e, m)
    #   -1.0 * t1(c, m) * v2iajb(m, d, n, a) * t1(b, n)
    #   1.0 * t1(d, m) * v2iajb(m, c, n, a) * t1(b, n)
    #   -(1.0/2.0) * t1(e, m) * v2abcd(a, e, c, d) * t1(b, m)
    #   1.0 * t1(c, m) * v2iajb(m, d, n, b) * t1(a, n)
    #   -1.0 * t1(d, m) * v2iajb(m, c, n, b) * t1(a, n)
    #   (1.0/2.0) * t1(e, m) * v2abcd(b, e, c, d) * t1(a, m)
    #   (1.0/2.0) * t1(d, m) * v2iabc(n, a, c, e) * t2(b, e, m, n)
    #   -(1.0/2.0) * t1(c, m) * v2iabc(n, a, d, e) * t2(b, e, m, n)
    #   (1.0/2.0) * t1(e, m) * v2iabc(n, a, d, c) * t2(b, e, m, n)
    #   -(1.0/2.0) * t1(d, m) * v2iabc(n, b, c, e) * t2(a, e, m, n)
    #   (1.0/2.0) * t1(c, m) * v2iabc(n, b, d, e) * t2(a, e, m, n)
    #   -(1.0/2.0) * t1(e, m) * v2iabc(n, b, d, c) * t2(a, e, m, n)
    #   -(1.0/2.0) * t1(c, m) * v2ijka(n, o, m, d) * t2(a, b, n, o)
    #   (1.0/2.0) * t1(d, m) * v2ijka(n, o, m, c) * t2(a, b, n, o)
    #   1.0 * t1(e, m) * v2iabc(n, e, d, c) * t2(a, b, m, n)
    #   (1.0/8.0) * t2(c, d, m, n) * v2abcd(a, b, e, f) * t2(e, f, m, n)
    #   (1.0/4.0) * t2(e, d, m, n) * v2abcd(a, b, f, c) * t2(e, f, m, n)
    #   -(1.0/4.0) * t2(e, c, m, n) * v2abcd(a, b, f, d) * t2(e, f, m, n)
    #   -1.0 * t2(e, c, m, n) * v2iajb(m, d, o, a) * t2(b, e, n, o)
    #   1.0 * t2(e, d, m, n) * v2iajb(m, c, o, a) * t2(b, e, n, o)
    #   -1.0 * t2(c, d, m, n) * v2iajb(m, e, o, a) * t2(b, e, n, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * v2abcd(a, e, c, d) * t2(b, f, m, n)
    #   (1.0/2.0) * t2(e, c, m, n) * v2abcd(a, e, f, d) * t2(b, f, m, n)
    #   -(1.0/2.0) * t2(e, d, m, n) * v2abcd(a, e, f, c) * t2(b, f, m, n)
    #   1.0 * t2(e, c, m, n) * v2iajb(m, d, o, b) * t2(a, e, n, o)
    #   -1.0 * t2(e, d, m, n) * v2iajb(m, c, o, b) * t2(a, e, n, o)
    #   1.0 * t2(c, d, m, n) * v2iajb(m, e, o, b) * t2(a, e, n, o)
    #   (1.0/4.0) * t2(e, f, m, n) * v2abcd(b, e, c, d) * t2(a, f, m, n)
    #   -(1.0/2.0) * t2(e, c, m, n) * v2abcd(b, e, f, d) * t2(a, f, m, n)
    #   (1.0/2.0) * t2(e, d, m, n) * v2abcd(b, e, f, c) * t2(a, f, m, n)
    #   -1.0 * t2(e, c, m, n) * v2iajb(m, d, o, e) * t2(a, b, n, o)
    #   1.0 * t2(e, d, m, n) * v2iajb(m, c, o, e) * t2(a, b, n, o)
    #   (1.0/4.0) * t2(c, d, m, n) * v2ijkl(o, p, m, n) * t2(a, b, o, p)
    #   (1.0/8.0) * t2(e, f, m, n) * v2abcd(e, f, c, d) * t2(a, b, m, n)
    #   (1.0/2.0) * t2(e, c, m, n) * v2iabc(m, d, a, b) * t1(e, n)
    #   -(1.0/2.0) * t2(e, d, m, n) * v2iabc(m, c, a, b) * t1(e, n)
    #   1.0 * t2(c, d, m, n) * v2iabc(m, e, a, b) * t1(e, n)
    #   -(1.0/2.0) * t2(e, c, m, n) * v2iabc(m, d, a, e) * t1(b, n)
    #   (1.0/2.0) * t2(e, d, m, n) * v2iabc(m, c, a, e) * t1(b, n)
    #   -(1.0/2.0) * t2(c, d, m, n) * v2ijka(n, m, o, a) * t1(b, o)
    #   (1.0/2.0) * t2(e, c, m, n) * v2iabc(m, d, b, e) * t1(a, n)
    #   -(1.0/2.0) * t2(e, d, m, n) * v2iabc(m, c, b, e) * t1(a, n)
    #   (1.0/2.0) * t2(c, d, m, n) * v2ijka(n, m, o, b) * t1(a, o)
    #   1.0 * t1(c, m) * t1(d, n) * v2ijab(m, n, a, b)



# def F_3(Fock_Trans, V_Trans, t1, t2, f, g, o, v):

    #   HH  ------------------------------------------------------------
    #   -(1.0/2.0) * t1(e, i) * f1_OV(m, f) * t1(f, j) * t1(e, m)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(i, f) * t1(e, j) * t1(f, m)
    #   -(1.0/4.0) * t2(e, f, m, i) * f1_OV(n, g) * t1(g, j) * t2(e, f, m, n)
    #   -(1.0/6.0) * t2(e, f, m, i) * f1_OV(n, g) * t1(e, j) * t2(f, g, m, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OV(i, g) * t1(e, j) * t2(f, g, m, n)
    #   -(2.0/3.0) * t2(e, f, m, i) * f1_OV(n, g) * t1(e, n) * t2(f, g, j, m)
    #   (1.0/3.0) * t2(e, f, m, i) * f1_OV(n, g) * t1(g, m) * t2(e, f, j, n)
    #   (1.0/6.0) * t2(e, f, m, i) * f1_OV(n, g) * t1(e, m) * t2(f, g, j, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OV(i, g) * t1(g, m) * t2(e, f, j, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OV(i, g) * t1(e, m) * t2(f, g, j, n)
    #   (1.0/3.0) * f1_OO(m, j) * t1(e, n) * t1(f, i) * t2(e, f, m, n)
    #   (1.0/2.0) * t1(e, m) * t1(f, i) * f1_OO(n, m) * t2(e, f, j, n)
    #   -(1.0/6.0) * t1(e, m) * t1(f, n) * f1_OO(i, m) * t2(e, f, j, n)
    #   (1.0/2.0) * t1(e, m) * t1(f, i) * f1_VV(e, g) * t2(f, g, j, m)
    #   -(1.0/2.0) * t1(e, m) * t1(f, i) * f1_VV(f, g) * t2(e, g, j, m)
    #   -(1.0/6.0) * t2(e, f, m, i) * f1_OO(n, j) * t1(e, m) * t1(f, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OO(i, m) * t1(e, j) * t1(f, n)
    #   (1.0/2.0) * t2(e, f, m, i) * f1_OO(n, m) * t1(e, j) * t1(f, n)
    #   (1.0/2.0) * t2(e, f, m, i) * f1_VV(e, g) * t1(f, j) * t1(g, m)
    #   -(1.0/2.0) * t2(e, f, m, i) * f1_VV(e, g) * t1(g, j) * t1(f, m)
    #   -(1.0/6.0) * t1(e, m) * t1(f, i) * f1_OV(j, e) * t1(f, m)
    #   -(1.0/2.0) * t1(e, m) * t1(f, i) * f1_OV(m, f) * t1(e, j)
    #   (1.0/12.0) * t1(e, m) * t2(f, g, n, i) * f1_OV(j, e) * t2(f, g, m, n)
    #   -(1.0/12.0) * t1(e, i) * t2(f, g, m, n) * f1_OV(j, f) * t2(e, g, m, n)
    #   -(1.0/6.0) * t1(e, m) * t2(f, g, n, i) * f1_OV(j, f) * t2(e, g, m, n)
    #   (1.0/6.0) * t1(e, i) * t2(f, g, m, n) * f1_OV(m, f) * t2(e, g, j, n)
    #   -(1.0/6.0) * t1(e, m) * t2(f, g, n, i) * f1_OV(n, f) * t2(e, g, j, m)
    #   (2.0/3.0) * t1(e, m) * t2(f, g, n, i) * f1_OV(m, f) * t2(e, g, j, n)
    #   (1.0/3.0) * t1(e, m) * t2(f, g, n, i) * f1_OV(n, e) * t2(f, g, j, m)
    #   -(1.0/4.0) * t1(e, i) * t2(f, g, m, n) * f1_OV(m, e) * t2(f, g, j, n)

    #   PP  ------------------------------------------------------------
    #   (1.0/2.0) * t1(b, m) * f1_OV(n, e) * t1(a, n) * t1(e, m)
    #   (1.0/6.0) * t1(e, m) * f1_OV(n, b) * t1(a, m) * t1(e, n)
    #   (1.0/4.0) * t2(e, b, m, n) * f1_OV(o, f) * t1(a, o) * t2(e, f, m, n)
    #   (1.0/6.0) * t2(e, b, m, n) * f1_OV(o, f) * t1(a, m) * t2(e, f, n, o)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OV(o, b) * t1(a, m) * t2(e, f, n, o)
    #   -(1.0/3.0) * t2(e, b, m, n) * f1_OV(o, f) * t1(e, o) * t2(a, f, m, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OV(o, b) * t1(e, o) * t2(a, f, m, n)
    #   (2.0/3.0) * t2(e, b, m, n) * f1_OV(o, f) * t1(f, m) * t2(a, e, n, o)
    #   -(1.0/6.0) * t2(e, b, m, n) * f1_OV(o, f) * t1(e, m) * t2(a, f, n, o)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OV(o, b) * t1(e, m) * t2(a, f, n, o)
    #   (1.0/3.0) * f1_VV(a, e) * t1(f, m) * t1(b, n) * t2(e, f, m, n)
    #   (1.0/2.0) * t1(e, m) * t1(b, n) * f1_OO(o, m) * t2(a, e, n, o)
    #   -(1.0/2.0) * t1(b, m) * t1(e, n) * f1_OO(o, m) * t2(a, e, n, o)
    #   (1.0/2.0) * t1(e, m) * t1(b, n) * f1_VV(e, f) * t2(a, f, m, n)
    #   -(1.0/6.0) * t1(e, m) * t1(f, n) * f1_VV(e, b) * t2(a, f, m, n)
    #   -(1.0/6.0) * t2(e, b, m, n) * f1_VV(a, f) * t1(e, m) * t1(f, n)
    #   (1.0/2.0) * t2(e, b, m, n) * f1_OO(o, m) * t1(a, n) * t1(e, o)
    #   -(1.0/2.0) * t2(e, b, m, n) * f1_OO(o, m) * t1(a, o) * t1(e, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_VV(e, b) * t1(a, m) * t1(f, n)
    #   (1.0/2.0) * t2(e, b, m, n) * f1_VV(e, f) * t1(a, m) * t1(f, n)
    #   (1.0/6.0) * t1(e, m) * t1(b, n) * f1_OV(m, a) * t1(e, n)
    #   (1.0/2.0) * t1(b, m) * t1(e, n) * f1_OV(m, e) * t1(a, n)
    #   -(1.0/12.0) * t1(e, m) * t2(f, b, n, o) * f1_OV(m, a) * t2(e, f, n, o)
    #   (1.0/12.0) * t1(b, m) * t2(e, f, n, o) * f1_OV(n, a) * t2(e, f, m, o)
    #   (1.0/6.0) * t1(e, m) * t2(f, b, n, o) * f1_OV(n, a) * t2(e, f, m, o)
    #   -(1.0/6.0) * t1(b, m) * t2(e, f, n, o) * f1_OV(n, e) * t2(a, f, m, o)
    #   (1.0/6.0) * t1(e, m) * t2(f, b, n, o) * f1_OV(n, f) * t2(a, e, m, o)
    #   -(1.0/3.0) * t1(e, m) * t2(f, b, n, o) * f1_OV(m, f) * t2(a, e, n, o)
    #   (1.0/4.0) * t1(b, m) * t2(e, f, n, o) * f1_OV(m, e) * t2(a, f, n, o)
    #   -(2.0/3.0) * t1(e, m) * t2(f, b, n, o) * f1_OV(n, e) * t2(a, f, m, o)

    #   PH  ------------------------------------------------------------
    #   (1.0/2.0) * t1(e, m) * f1_OV(n, f) * t1(f, i) * t2(a, e, m, n)
    #   (1.0/2.0) * t1(e, m) * f1_OV(n, f) * t1(a, n) * t2(e, f, i, m)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(n, f) * t1(e, i) * t2(a, f, m, n)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(n, f) * t1(a, m) * t2(e, f, i, n)
    #   -(2.0/3.0) * t1(e, m) * f1_OV(n, f) * t1(e, n) * t2(a, f, i, m)
    #   -(2.0/3.0) * t1(e, m) * f1_OV(n, f) * t1(f, m) * t2(a, e, i, n)
    #   (1.0/6.0) * t1(e, m) * f1_OO(n, i) * t1(a, m) * t1(e, n)
    #   -(1.0/6.0) * t1(e, m) * f1_VV(a, f) * t1(e, i) * t1(f, m)
    #   (1.0/2.0) * t1(e, m) * f1_OO(n, m) * t1(e, i) * t1(a, n)
    #   -(1.0/2.0) * t1(e, m) * f1_VV(e, f) * t1(f, i) * t1(a, m)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OO(o, i) * t1(a, m) * t2(e, f, n, o)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OO(o, i) * t1(e, o) * t2(a, f, m, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OO(o, i) * t1(e, m) * t2(a, f, n, o)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_VV(a, g) * t1(e, i) * t2(f, g, m, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_VV(a, g) * t1(g, m) * t2(e, f, i, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_VV(a, g) * t1(e, m) * t2(f, g, i, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t1(e, i) * t2(a, f, n, o)
    #   (1.0/4.0) * t2(e, f, m, n) * f1_VV(e, g) * t1(f, i) * t2(a, g, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_VV(e, g) * t1(g, i) * t2(a, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_OO(o, m) * t1(a, n) * t2(e, f, i, o)
    #   (1.0/4.0) * t2(e, f, m, n) * f1_OO(o, m) * t1(a, o) * t2(e, f, i, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t1(a, m) * t2(f, g, i, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t1(e, n) * t2(a, f, i, o)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t1(e, o) * t2(a, f, i, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t1(f, m) * t2(a, g, i, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t1(g, m) * t2(a, f, i, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(o, g) * t2(a, e, i, o) * t2(f, g, m, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(o, g) * t2(a, g, i, m) * t2(e, f, n, o)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OV(o, g) * t2(a, e, i, m) * t2(f, g, n, o)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OV(o, g) * t2(e, g, i, o) * t2(a, f, m, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OV(o, g) * t2(e, f, i, o) * t2(a, g, m, n)
    #   -(2.0/3.0) * t2(e, f, m, n) * f1_OV(o, g) * t2(e, g, i, m) * t2(a, f, n, o)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OV(o, g) * t2(e, f, i, m) * t2(a, g, n, o)
    #   -(1.0/6.0) * t1(e, m) * t1(f, n) * f1_OV(i, e) * t2(a, f, m, n)
    #   -(1.0/6.0) * t1(e, m) * t1(f, n) * f1_OV(m, a) * t2(e, f, i, n)
    #   -(2.0/3.0) * t1(e, m) * t1(f, n) * f1_OV(m, f) * t2(a, e, i, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(i, e) * t1(a, m) * t1(f, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(m, a) * t1(e, i) * t1(f, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(m, e) * t1(f, i) * t1(a, n)

    #   HHHH -----------------------------------------------------------
    #   (1.0/4.0) * t2(e, f, i, j) * f1_OV(m, g) * t1(g, k) * t2(e, f, l, m)
    #   -(1.0/4.0) * t2(e, f, i, j) * f1_OV(m, g) * t1(g, l) * t2(e, f, k, m)
    #   (1.0/6.0) * t2(e, f, i, j) * f1_OV(m, g) * t1(e, k) * t2(f, g, l, m)
    #   -(1.0/6.0) * t2(e, f, m, j) * f1_OV(i, g) * t1(e, k) * t2(f, g, l, m)
    #   (1.0/6.0) * t2(e, f, m, i) * f1_OV(j, g) * t1(e, k) * t2(f, g, l, m)
    #   -(1.0/6.0) * t2(e, f, i, j) * f1_OV(m, g) * t1(e, l) * t2(f, g, k, m)
    #   (1.0/6.0) * t2(e, f, m, j) * f1_OV(i, g) * t1(e, l) * t2(f, g, k, m)
    #   -(1.0/6.0) * t2(e, f, m, i) * f1_OV(j, g) * t1(e, l) * t2(f, g, k, m)
    #   (2.0/3.0) * t2(e, f, i, j) * f1_OV(m, g) * t1(e, m) * t2(f, g, k, l)
    #   -(1.0/12.0) * t2(e, f, m, j) * f1_OV(i, g) * t1(g, m) * t2(e, f, k, l)
    #   -(1.0/6.0) * t2(e, f, m, j) * f1_OV(i, g) * t1(e, m) * t2(f, g, k, l)
    #   (1.0/12.0) * t2(e, f, m, i) * f1_OV(j, g) * t1(g, m) * t2(e, f, k, l)
    #   (1.0/6.0) * t2(e, f, m, i) * f1_OV(j, g) * t1(e, m) * t2(f, g, k, l)
    #   (1.0/3.0) * f1_OO(m, k) * t1(e, i) * t1(f, j) * t2(e, f, l, m)
    #   -(1.0/3.0) * f1_OO(m, l) * t1(e, i) * t1(f, j) * t2(e, f, k, m)
    #   -(1.0/6.0) * t1(e, m) * t1(f, j) * f1_OO(i, m) * t2(e, f, k, l)
    #   (1.0/6.0) * t1(e, m) * t1(f, i) * f1_OO(j, m) * t2(e, f, k, l)
    #   -(1.0/2.0) * t1(e, i) * t1(f, j) * f1_VV(e, g) * t2(f, g, k, l)
    #   (1.0/2.0) * t1(e, i) * t1(f, j) * f1_VV(f, g) * t2(e, g, k, l)
    #   (1.0/6.0) * t2(e, f, i, j) * f1_OO(m, k) * t1(e, l) * t1(f, m)
    #   -(1.0/6.0) * t2(e, f, i, j) * f1_OO(m, l) * t1(e, k) * t1(f, m)
    #   (1.0/3.0) * t2(e, f, m, i) * f1_OO(j, m) * t1(e, k) * t1(f, l)
    #   -(1.0/3.0) * t2(e, f, m, j) * f1_OO(i, m) * t1(e, k) * t1(f, l)
    #   -(1.0/2.0) * t2(e, f, i, j) * f1_VV(e, g) * t1(f, k) * t1(g, l)
    #   (1.0/2.0) * t2(e, f, i, j) * f1_VV(e, g) * t1(g, k) * t1(f, l)
    #   (1.0/12.0) * t1(e, m) * t2(f, g, i, j) * f1_OV(k, e) * t2(f, g, l, m)
    #   -(1.0/12.0) * t1(e, m) * t2(f, g, i, j) * f1_OV(l, e) * t2(f, g, k, m)
    #   -(1.0/6.0) * t1(e, j) * t2(f, g, m, i) * f1_OV(k, f) * t2(e, g, l, m)
    #   (1.0/6.0) * t1(e, i) * t2(f, g, m, j) * f1_OV(k, f) * t2(e, g, l, m)
    #   -(1.0/6.0) * t1(e, m) * t2(f, g, i, j) * f1_OV(k, f) * t2(e, g, l, m)
    #   (1.0/6.0) * t1(e, j) * t2(f, g, m, i) * f1_OV(l, f) * t2(e, g, k, m)
    #   -(1.0/6.0) * t1(e, i) * t2(f, g, m, j) * f1_OV(l, f) * t2(e, g, k, m)
    #   (1.0/6.0) * t1(e, m) * t2(f, g, i, j) * f1_OV(l, f) * t2(e, g, k, m)
    #   -(1.0/6.0) * t1(e, j) * t2(f, g, m, i) * f1_OV(m, f) * t2(e, g, k, l)
    #   (1.0/6.0) * t1(e, i) * t2(f, g, m, j) * f1_OV(m, f) * t2(e, g, k, l)
    #   -(2.0/3.0) * t1(e, m) * t2(f, g, i, j) * f1_OV(m, f) * t2(e, g, k, l)
    #   -(1.0/4.0) * t1(e, i) * t2(f, g, m, j) * f1_OV(m, e) * t2(f, g, k, l)
    #   (1.0/4.0) * t1(e, j) * t2(f, g, m, i) * f1_OV(m, e) * t2(f, g, k, l)

    #   HHHP -----------------------------------------------------------
    #   (1.0/2.0) * t1(e, k) * f1_OV(m, f) * t1(f, j) * t2(a, e, i, m)
    #   (1.0/2.0) * t1(e, k) * f1_OV(m, f) * t1(a, m) * t2(e, f, j, i)
    #   -(1.0/2.0) * t1(e, k) * f1_OV(m, f) * t1(f, i) * t2(a, e, j, m)
    #   (1.0/6.0) * t1(e, m) * f1_OV(k, f) * t1(e, j) * t2(a, f, i, m)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(k, f) * t1(a, m) * t2(e, f, j, i)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(k, f) * t1(e, i) * t2(a, f, j, m)
    #   -(1.0/2.0) * t1(e, k) * f1_OV(m, f) * t1(e, m) * t2(a, f, j, i)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(k, f) * t1(f, m) * t2(a, e, j, i)
    #   -(1.0/4.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(a, g, j, i) * t2(e, f, m, n)
    #   -(1.0/6.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(a, e, j, i) * t2(f, g, m, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OV(k, g) * t2(a, e, j, i) * t2(f, g, m, n)
    #   -(2.0/3.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(a, e, j, n) * t2(f, g, i, m)
    #   (1.0/3.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(a, g, j, m) * t2(e, f, i, n)
    #   (1.0/6.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(a, e, j, m) * t2(f, g, i, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OV(k, g) * t2(a, g, j, m) * t2(e, f, i, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OV(k, g) * t2(a, e, j, m) * t2(f, g, i, n)
    #   (2.0/3.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(e, g, j, i) * t2(a, f, m, n)
    #   -(1.0/12.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(e, f, j, i) * t2(a, g, m, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OV(k, g) * t2(e, g, j, i) * t2(a, f, m, n)
    #   (1.0/24.0) * t2(e, f, m, n) * f1_OV(k, g) * t2(e, f, j, i) * t2(a, g, m, n)
    #   (1.0/6.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(e, g, j, n) * t2(a, f, i, m)
    #   -(1.0/3.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(e, f, j, n) * t2(a, g, i, m)
    #   -(2.0/3.0) * t2(e, f, m, k) * f1_OV(n, g) * t2(e, g, j, m) * t2(a, f, i, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OV(k, g) * t2(e, g, j, m) * t2(a, f, i, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OV(k, g) * t2(e, f, j, m) * t2(a, g, i, n)
    #   -(1.0/12.0) * t2(e, f, m, k) * f1_OO(n, j) * t1(a, m) * t2(e, f, i, n)
    #   -(1.0/6.0) * t2(e, f, m, k) * f1_OO(n, j) * t1(e, i) * t2(a, f, m, n)
    #   -(1.0/6.0) * t2(e, f, m, k) * f1_OO(n, j) * t1(e, n) * t2(a, f, i, m)
    #   (1.0/6.0) * t2(e, f, m, k) * f1_OO(n, j) * t1(e, m) * t2(a, f, i, n)
    #   -(1.0/6.0) * t2(e, f, m, k) * f1_VV(a, g) * t1(e, j) * t2(f, g, i, m)
    #   (1.0/6.0) * t2(e, f, m, k) * f1_OO(n, i) * t1(e, j) * t2(a, f, m, n)
    #   (1.0/6.0) * t2(e, f, m, k) * f1_VV(a, g) * t1(e, i) * t2(f, g, j, m)
    #   -(1.0/12.0) * t2(e, f, m, k) * f1_VV(a, g) * t1(g, m) * t2(e, f, j, i)
    #   -(1.0/6.0) * t2(e, f, m, k) * f1_VV(a, g) * t1(e, m) * t2(f, g, j, i)
    #   (1.0/12.0) * t2(e, f, m, k) * f1_OO(n, i) * t1(a, m) * t2(e, f, j, n)
    #   (1.0/6.0) * t2(e, f, m, k) * f1_OO(n, i) * t1(e, n) * t2(a, f, j, m)
    #   -(1.0/6.0) * t2(e, f, m, k) * f1_OO(n, i) * t1(e, m) * t2(a, f, j, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OO(k, m) * t1(e, j) * t2(a, f, i, n)
    #   -(1.0/2.0) * t2(e, f, m, k) * f1_OO(n, m) * t1(e, j) * t2(a, f, i, n)
    #   -(1.0/2.0) * t2(e, f, m, k) * f1_VV(e, g) * t1(f, j) * t2(a, g, i, m)
    #   (1.0/2.0) * t2(e, f, m, k) * f1_VV(e, g) * t1(g, j) * t2(a, f, i, m)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OO(k, m) * t1(a, n) * t2(e, f, j, i)
    #   (1.0/4.0) * t2(e, f, m, k) * f1_OO(n, m) * t1(a, n) * t2(e, f, j, i)
    #   (1.0/2.0) * t2(e, f, m, k) * f1_VV(e, g) * t1(a, m) * t2(f, g, j, i)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OO(k, m) * t1(e, i) * t2(a, f, j, n)
    #   (1.0/2.0) * t2(e, f, m, k) * f1_OO(n, m) * t1(e, i) * t2(a, f, j, n)
    #   (1.0/2.0) * t2(e, f, m, k) * f1_VV(e, g) * t1(f, i) * t2(a, g, j, m)
    #   -(1.0/2.0) * t2(e, f, m, k) * f1_VV(e, g) * t1(g, i) * t2(a, f, j, m)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OO(k, m) * t1(e, n) * t2(a, f, j, i)
    #   -(1.0/2.0) * t2(e, f, m, k) * f1_OO(n, m) * t1(e, n) * t2(a, f, j, i)
    #   -(1.0/2.0) * t2(e, f, m, k) * f1_VV(e, g) * t1(f, m) * t2(a, g, j, i)
    #   (1.0/2.0) * t2(e, f, m, k) * f1_VV(e, g) * t1(g, m) * t2(a, f, j, i)
    #   (1.0/6.0) * t1(e, m) * t1(f, k) * f1_OV(j, e) * t2(a, f, i, m)
    #   -(1.0/6.0) * t1(e, m) * t1(f, k) * f1_OV(m, a) * t2(e, f, j, i)
    #   -(1.0/6.0) * t1(e, m) * t1(f, k) * f1_OV(i, e) * t2(a, f, j, m)
    #   -(1.0/2.0) * t1(e, m) * t1(f, k) * f1_OV(m, f) * t2(a, e, j, i)
    #   -(1.0/3.0) * t2(e, f, m, k) * f1_OV(j, e) * t1(a, m) * t1(f, i)
    #   -(1.0/3.0) * t2(e, f, m, k) * f1_OV(m, a) * t1(e, j) * t1(f, i)
    #   (1.0/3.0) * t2(e, f, m, k) * f1_OV(i, e) * t1(f, j) * t1(a, m)

    #   HHPP -----------------------------------------------------------
    #   (1.0/6.0) * t1(e, m) * f1_OO(n, i) * t1(a, m) * t2(b, e, j, n)
    #   -(1.0/6.0) * t1(e, m) * f1_OO(n, i) * t1(e, j) * t2(a, b, m, n)
    #   -(1.0/6.0) * t1(e, m) * f1_OO(n, i) * t1(b, m) * t2(a, e, j, n)
    #   -(1.0/6.0) * t1(e, m) * f1_OO(n, i) * t1(e, n) * t2(a, b, j, m)
    #   -(1.0/6.0) * t1(e, m) * f1_VV(a, f) * t1(e, i) * t2(b, f, j, m)
    #   (1.0/6.0) * t1(e, m) * f1_OO(n, j) * t1(e, i) * t2(a, b, m, n)
    #   (1.0/6.0) * t1(e, m) * f1_VV(b, f) * t1(e, i) * t2(a, f, j, m)
    #   (1.0/6.0) * t1(e, m) * f1_VV(a, f) * t1(e, j) * t2(b, f, i, m)
    #   (1.0/6.0) * t1(e, m) * f1_VV(a, f) * t1(b, m) * t2(e, f, i, j)
    #   (1.0/6.0) * t1(e, m) * f1_VV(a, f) * t1(f, m) * t2(b, e, i, j)
    #   -(1.0/6.0) * t1(e, m) * f1_OO(n, j) * t1(a, m) * t2(b, e, i, n)
    #   -(1.0/6.0) * t1(e, m) * f1_VV(b, f) * t1(a, m) * t2(e, f, i, j)
    #   (1.0/6.0) * t1(e, m) * f1_OO(n, j) * t1(b, m) * t2(a, e, i, n)
    #   (1.0/6.0) * t1(e, m) * f1_OO(n, j) * t1(e, n) * t2(a, b, i, m)
    #   -(1.0/6.0) * t1(e, m) * f1_VV(b, f) * t1(e, j) * t2(a, f, i, m)
    #   -(1.0/6.0) * t1(e, m) * f1_VV(b, f) * t1(f, m) * t2(a, e, i, j)
    #   -(1.0/2.0) * t1(e, m) * f1_OO(n, m) * t1(e, i) * t2(a, b, j, n)
    #   (1.0/2.0) * t1(e, m) * f1_VV(e, f) * t1(f, i) * t2(a, b, j, m)
    #   -(1.0/2.0) * t1(e, m) * f1_OO(n, m) * t1(a, n) * t2(b, e, i, j)
    #   (1.0/2.0) * t1(e, m) * f1_VV(e, f) * t1(a, m) * t2(b, f, i, j)
    #   (1.0/2.0) * t1(e, m) * f1_OO(n, m) * t1(e, j) * t2(a, b, i, n)
    #   -(1.0/2.0) * t1(e, m) * f1_VV(e, f) * t1(f, j) * t2(a, b, i, m)
    #   (1.0/2.0) * t1(e, m) * f1_OO(n, m) * t1(b, n) * t2(a, e, i, j)
    #   -(1.0/2.0) * t1(e, m) * f1_VV(e, f) * t1(b, m) * t2(a, f, i, j)
    #   (1.0/2.0) * t1(e, m) * f1_OV(n, f) * t2(a, f, i, j) * t2(b, e, m, n)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(n, f) * t2(a, e, i, j) * t2(b, f, m, n)
    #   (1.0/2.0) * t1(e, m) * f1_OV(n, f) * t2(a, b, i, n) * t2(e, f, j, m)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(n, f) * t2(a, b, i, m) * t2(e, f, j, n)
    #   -(2.0/3.0) * t1(e, m) * f1_OV(n, f) * t2(a, e, i, n) * t2(b, f, j, m)
    #   -(2.0/3.0) * t1(e, m) * f1_OV(n, f) * t2(a, f, i, m) * t2(b, e, j, n)
    #   -(1.0/2.0) * t1(e, m) * f1_OV(n, f) * t2(b, f, i, j) * t2(a, e, m, n)
    #   (1.0/6.0) * t1(e, m) * f1_OV(n, f) * t2(b, e, i, j) * t2(a, f, m, n)
    #   (2.0/3.0) * t1(e, m) * f1_OV(n, f) * t2(e, f, i, j) * t2(a, b, m, n)
    #   (2.0/3.0) * t1(e, m) * f1_OV(n, f) * t2(b, e, i, n) * t2(a, f, j, m)
    #   (2.0/3.0) * t1(e, m) * f1_OV(n, f) * t2(b, f, i, m) * t2(a, e, j, n)
    #   (1.0/6.0) * t1(e, m) * f1_OV(n, f) * t2(e, f, i, n) * t2(a, b, j, m)
    #   -(1.0/2.0) * t1(e, m) * f1_OV(n, f) * t2(e, f, i, m) * t2(a, b, j, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OO(o, i) * t2(a, b, j, m) * t2(e, f, n, o)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OO(o, i) * t2(a, e, j, o) * t2(b, f, m, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OO(o, i) * t2(a, e, j, m) * t2(b, f, n, o)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OO(o, i) * t2(a, b, m, o) * t2(e, f, j, n)
    #   (1.0/24.0) * t2(e, f, m, n) * f1_OO(o, i) * t2(a, b, m, n) * t2(e, f, j, o)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OO(o, i) * t2(a, e, m, o) * t2(b, f, j, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OO(o, i) * t2(a, e, m, n) * t2(b, f, j, o)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_VV(a, g) * t2(b, e, i, j) * t2(f, g, m, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_VV(a, g) * t2(e, g, i, j) * t2(b, f, m, n)
    #   -(1.0/24.0) * t2(e, f, m, n) * f1_VV(a, g) * t2(e, f, i, j) * t2(b, g, m, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_VV(a, g) * t2(b, g, i, m) * t2(e, f, j, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_VV(a, g) * t2(b, e, i, m) * t2(f, g, j, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_VV(a, g) * t2(e, g, i, m) * t2(b, f, j, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_VV(a, g) * t2(e, f, i, m) * t2(b, g, j, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OO(o, j) * t2(a, b, i, m) * t2(e, f, n, o)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OO(o, j) * t2(a, e, i, o) * t2(b, f, m, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OO(o, j) * t2(a, e, i, m) * t2(b, f, n, o)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_VV(b, g) * t2(a, e, i, j) * t2(f, g, m, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_VV(b, g) * t2(a, g, i, m) * t2(e, f, j, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_VV(b, g) * t2(a, e, i, m) * t2(f, g, j, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OO(o, j) * t2(b, e, i, o) * t2(a, f, m, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OO(o, j) * t2(b, e, i, m) * t2(a, f, n, o)
    #   -(1.0/24.0) * t2(e, f, m, n) * f1_OO(o, j) * t2(e, f, i, o) * t2(a, b, m, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OO(o, j) * t2(e, f, i, m) * t2(a, b, n, o)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_VV(b, g) * t2(e, g, i, j) * t2(a, f, m, n)
    #   (1.0/24.0) * t2(e, f, m, n) * f1_VV(b, g) * t2(e, f, i, j) * t2(a, g, m, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_VV(b, g) * t2(e, g, i, m) * t2(a, f, j, n)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_VV(b, g) * t2(e, f, i, m) * t2(a, g, j, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(a, e, i, j) * t2(b, f, n, o)
    #   (1.0/4.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(a, f, i, j) * t2(b, g, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(a, g, i, j) * t2(b, f, m, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(a, b, i, n) * t2(e, f, j, o)
    #   (1.0/4.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(a, b, i, o) * t2(e, f, j, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(a, b, i, m) * t2(f, g, j, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(a, e, i, n) * t2(b, f, j, o)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(a, e, i, o) * t2(b, f, j, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(a, f, i, m) * t2(b, g, j, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(a, g, i, m) * t2(b, f, j, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(b, e, i, j) * t2(a, f, n, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(b, f, i, j) * t2(a, g, m, n)
    #   (1.0/4.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(b, g, i, j) * t2(a, f, m, n)
    #   (1.0/4.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(e, f, i, j) * t2(a, b, n, o)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(f, g, i, j) * t2(a, b, m, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(b, e, i, n) * t2(a, f, j, o)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(b, e, i, o) * t2(a, f, j, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(b, f, i, m) * t2(a, g, j, n)
    #   -(1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(b, g, i, m) * t2(a, f, j, n)
    #   -(1.0/4.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(e, f, i, n) * t2(a, b, j, o)
    #   (1.0/4.0) * t2(e, f, m, n) * f1_OO(o, m) * t2(e, f, i, o) * t2(a, b, j, n)
    #   (1.0/2.0) * t2(e, f, m, n) * f1_VV(e, g) * t2(f, g, i, m) * t2(a, b, j, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(i, e) * t1(a, m) * t2(b, f, j, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OV(i, e) * t1(f, j) * t2(a, b, m, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(i, e) * t1(b, m) * t2(a, f, j, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(i, e) * t1(f, m) * t2(a, b, j, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(m, a) * t1(e, i) * t2(b, f, j, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OV(j, e) * t1(f, i) * t2(a, b, m, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(m, b) * t1(e, i) * t2(a, f, j, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(m, e) * t1(f, i) * t2(a, b, j, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(m, a) * t1(e, j) * t2(b, f, i, n)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OV(m, a) * t1(b, n) * t2(e, f, i, j)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(m, a) * t1(e, n) * t2(b, f, i, j)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(j, e) * t1(a, m) * t2(b, f, i, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OV(m, b) * t1(a, n) * t2(e, f, i, j)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(m, e) * t1(a, n) * t2(b, f, i, j)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(j, e) * t1(b, m) * t2(a, f, i, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(j, e) * t1(f, m) * t2(a, b, i, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(m, b) * t1(e, j) * t2(a, f, i, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(m, e) * t1(f, j) * t2(a, b, i, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_OV(m, b) * t1(e, n) * t2(a, f, i, j)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_OV(m, e) * t1(b, n) * t2(a, f, i, j)

    #   HPHP -----------------------------------------------------------
    #   -(1.0/2.0) * t2(e, b, m, i) * f1_OV(n, f) * t1(f, j) * t2(a, e, m, n)
    #   -(1.0/2.0) * t2(e, b, m, i) * f1_OV(n, f) * t1(a, n) * t2(e, f, j, m)
    #   (1.0/6.0) * t2(e, b, m, i) * f1_OV(n, f) * t1(e, j) * t2(a, f, m, n)
    #   -(1.0/6.0) * t2(e, f, m, i) * f1_OV(n, b) * t1(e, j) * t2(a, f, m, n)
    #   -(1.0/12.0) * t2(e, b, m, n) * f1_OV(i, f) * t1(e, j) * t2(a, f, m, n)
    #   (1.0/6.0) * t2(e, b, m, i) * f1_OV(n, f) * t1(a, m) * t2(e, f, j, n)
    #   -(1.0/12.0) * t2(e, f, m, i) * f1_OV(n, b) * t1(a, m) * t2(e, f, j, n)
    #   -(1.0/6.0) * t2(e, b, m, n) * f1_OV(i, f) * t1(a, m) * t2(e, f, j, n)
    #   (2.0/3.0) * t2(e, b, m, i) * f1_OV(n, f) * t1(e, n) * t2(a, f, j, m)
    #   -(1.0/6.0) * t2(e, f, m, i) * f1_OV(n, b) * t1(e, n) * t2(a, f, j, m)
    #   (2.0/3.0) * t2(e, b, m, i) * f1_OV(n, f) * t1(f, m) * t2(a, e, j, n)
    #   (1.0/6.0) * t2(e, f, m, i) * f1_OV(n, b) * t1(e, m) * t2(a, f, j, n)
    #   -(1.0/6.0) * t2(e, b, m, n) * f1_OV(i, f) * t1(f, m) * t2(a, e, j, n)
    #   (1.0/6.0) * t2(e, b, m, n) * f1_OV(i, f) * t1(e, m) * t2(a, f, j, n)
    #   -(1.0/3.0) * f1_OO(m, j) * t1(b, n) * t1(e, i) * t2(a, e, m, n)
    #   (1.0/3.0) * f1_VV(a, e) * t1(b, m) * t1(f, i) * t2(e, f, j, m)
    #   -(1.0/6.0) * t1(e, m) * t1(b, n) * f1_OO(i, m) * t2(a, e, j, n)
    #   -(1.0/2.0) * t1(b, m) * t1(e, i) * f1_OO(n, m) * t2(a, e, j, n)
    #   (1.0/6.0) * t1(e, m) * t1(f, i) * f1_VV(e, b) * t2(a, f, j, m)
    #   (1.0/2.0) * t1(b, m) * t1(e, i) * f1_VV(e, f) * t2(a, f, j, m)
    #   -(1.0/6.0) * t2(e, b, m, i) * f1_OO(n, j) * t1(a, m) * t1(e, n)
    #   (1.0/6.0) * t2(e, b, m, i) * f1_VV(a, f) * t1(e, j) * t1(f, m)
    #   (1.0/3.0) * t2(e, b, m, n) * f1_OO(i, m) * t1(e, j) * t1(a, n)
    #   -(1.0/2.0) * t2(e, b, m, i) * f1_OO(n, m) * t1(e, j) * t1(a, n)
    #   -(1.0/3.0) * t2(e, f, m, i) * f1_VV(e, b) * t1(f, j) * t1(a, m)
    #   (1.0/2.0) * t2(e, b, m, i) * f1_VV(e, f) * t1(f, j) * t1(a, m)
    #   (1.0/6.0) * t1(e, m) * t2(f, b, n, i) * f1_OV(j, e) * t2(a, f, m, n)
    #   (1.0/6.0) * t1(e, m) * t2(f, b, n, i) * f1_OV(m, a) * t2(e, f, j, n)
    #   -(1.0/12.0) * t1(e, i) * t2(f, b, m, n) * f1_OV(j, f) * t2(a, e, m, n)
    #   (1.0/6.0) * t1(b, m) * t2(e, f, n, i) * f1_OV(j, e) * t2(a, f, m, n)
    #   -(1.0/6.0) * t1(e, m) * t2(f, b, n, i) * f1_OV(j, f) * t2(a, e, m, n)
    #   (1.0/6.0) * t1(e, i) * t2(f, b, m, n) * f1_OV(m, a) * t2(e, f, j, n)
    #   -(1.0/12.0) * t1(b, m) * t2(e, f, n, i) * f1_OV(n, a) * t2(e, f, j, m)
    #   -(1.0/6.0) * t1(e, m) * t2(f, b, n, i) * f1_OV(n, a) * t2(e, f, j, m)
    #   (1.0/6.0) * t1(e, i) * t2(f, b, m, n) * f1_OV(m, f) * t2(a, e, j, n)
    #   (1.0/6.0) * t1(b, m) * t2(e, f, n, i) * f1_OV(n, e) * t2(a, f, j, m)
    #   (2.0/3.0) * t1(e, m) * t2(f, b, n, i) * f1_OV(m, f) * t2(a, e, j, n)
    #   -(1.0/2.0) * t1(b, m) * t2(e, f, n, i) * f1_OV(m, e) * t2(a, f, j, n)
    #   (2.0/3.0) * t1(e, m) * t2(f, b, n, i) * f1_OV(n, e) * t2(a, f, j, m)
    #   -(1.0/2.0) * t1(e, i) * t2(f, b, m, n) * f1_OV(m, e) * t2(a, f, j, n)

    #   HPPP -----------------------------------------------------------
    #   -(1.0/2.0) * t1(a, m) * f1_OV(n, e) * t1(b, n) * t2(c, e, i, m)
    #   -(1.0/2.0) * t1(a, m) * f1_OV(n, e) * t1(e, i) * t2(b, c, m, n)
    #   (1.0/2.0) * t1(a, m) * f1_OV(n, e) * t1(c, n) * t2(b, e, i, m)
    #   -(1.0/6.0) * t1(e, m) * f1_OV(n, a) * t1(b, m) * t2(c, e, i, n)
    #   (1.0/6.0) * t1(e, m) * f1_OV(n, a) * t1(e, i) * t2(b, c, m, n)
    #   (1.0/6.0) * t1(e, m) * f1_OV(n, a) * t1(c, m) * t2(b, e, i, n)
    #   (1.0/6.0) * t1(e, m) * f1_OV(n, a) * t1(e, n) * t2(b, c, i, m)
    #   (1.0/2.0) * t1(a, m) * f1_OV(n, e) * t1(e, m) * t2(b, c, i, n)
    #   (1.0/4.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, c, i, o) * t2(e, f, m, n)
    #   (1.0/6.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, c, i, m) * t2(e, f, n, o)
    #   -(1.0/12.0) * t2(e, f, m, n) * f1_OV(o, a) * t2(b, c, i, m) * t2(e, f, n, o)
    #   -(1.0/3.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, e, i, o) * t2(c, f, m, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OV(o, a) * t2(b, e, i, o) * t2(c, f, m, n)
    #   (2.0/3.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, f, i, m) * t2(c, e, n, o)
    #   -(1.0/6.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, e, i, m) * t2(c, f, n, o)
    #   (1.0/6.0) * t2(e, f, m, n) * f1_OV(o, a) * t2(b, e, i, m) * t2(c, f, n, o)
    #   -(2.0/3.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, c, m, o) * t2(e, f, i, n)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OV(o, a) * t2(b, c, m, o) * t2(e, f, i, n)
    #   (1.0/12.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, c, m, n) * t2(e, f, i, o)
    #   -(1.0/24.0) * t2(e, f, m, n) * f1_OV(o, a) * t2(b, c, m, n) * t2(e, f, i, o)
    #   -(1.0/6.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, f, m, o) * t2(c, e, i, n)
    #   (2.0/3.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, e, m, o) * t2(c, f, i, n)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_OV(o, a) * t2(b, e, m, o) * t2(c, f, i, n)
    #   (1.0/3.0) * t2(e, a, m, n) * f1_OV(o, f) * t2(b, f, m, n) * t2(c, e, i, o)
    #   (1.0/12.0) * t2(e, f, m, n) * f1_OV(o, a) * t2(b, e, m, n) * t2(c, f, i, o)
    #   -(1.0/12.0) * t2(e, a, m, n) * f1_VV(b, f) * t1(e, i) * t2(c, f, m, n)
    #   -(1.0/6.0) * t2(e, a, m, n) * f1_VV(b, f) * t1(c, m) * t2(e, f, i, n)
    #   -(1.0/6.0) * t2(e, a, m, n) * f1_VV(b, f) * t1(f, m) * t2(c, e, i, n)
    #   (1.0/6.0) * t2(e, a, m, n) * f1_VV(b, f) * t1(e, m) * t2(c, f, i, n)
    #   -(1.0/6.0) * t2(e, a, m, n) * f1_OO(o, i) * t1(b, m) * t2(c, e, n, o)
    #   (1.0/6.0) * t2(e, a, m, n) * f1_VV(c, f) * t1(b, m) * t2(e, f, i, n)
    #   (1.0/6.0) * t2(e, a, m, n) * f1_OO(o, i) * t1(c, m) * t2(b, e, n, o)
    #   -(1.0/12.0) * t2(e, a, m, n) * f1_OO(o, i) * t1(e, o) * t2(b, c, m, n)
    #   -(1.0/6.0) * t2(e, a, m, n) * f1_OO(o, i) * t1(e, m) * t2(b, c, n, o)
    #   (1.0/12.0) * t2(e, a, m, n) * f1_VV(c, f) * t1(e, i) * t2(b, f, m, n)
    #   (1.0/6.0) * t2(e, a, m, n) * f1_VV(c, f) * t1(f, m) * t2(b, e, i, n)
    #   -(1.0/6.0) * t2(e, a, m, n) * f1_VV(c, f) * t1(e, m) * t2(b, f, i, n)
    #   -(1.0/2.0) * t2(e, a, m, n) * f1_OO(o, m) * t1(b, n) * t2(c, e, i, o)
    #   (1.0/2.0) * t2(e, a, m, n) * f1_OO(o, m) * t1(b, o) * t2(c, e, i, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_VV(e, a) * t1(b, m) * t2(c, f, i, n)
    #   -(1.0/2.0) * t2(e, a, m, n) * f1_VV(e, f) * t1(b, m) * t2(c, f, i, n)
    #   (1.0/2.0) * t2(e, a, m, n) * f1_OO(o, m) * t1(e, i) * t2(b, c, n, o)
    #   -(1.0/6.0) * t2(e, f, m, n) * f1_VV(e, a) * t1(f, i) * t2(b, c, m, n)
    #   (1.0/4.0) * t2(e, a, m, n) * f1_VV(e, f) * t1(f, i) * t2(b, c, m, n)
    #   (1.0/2.0) * t2(e, a, m, n) * f1_OO(o, m) * t1(c, n) * t2(b, e, i, o)
    #   -(1.0/2.0) * t2(e, a, m, n) * f1_OO(o, m) * t1(c, o) * t2(b, e, i, n)
    #   -(1.0/3.0) * t2(e, f, m, n) * f1_VV(e, a) * t1(c, m) * t2(b, f, i, n)
    #   (1.0/2.0) * t2(e, a, m, n) * f1_VV(e, f) * t1(c, m) * t2(b, f, i, n)
    #   -(1.0/2.0) * t2(e, a, m, n) * f1_OO(o, m) * t1(e, n) * t2(b, c, i, o)
    #   (1.0/2.0) * t2(e, a, m, n) * f1_OO(o, m) * t1(e, o) * t2(b, c, i, n)
    #   (1.0/3.0) * t2(e, f, m, n) * f1_VV(e, a) * t1(f, m) * t2(b, c, i, n)
    #   -(1.0/2.0) * t2(e, a, m, n) * f1_VV(e, f) * t1(f, m) * t2(b, c, i, n)
    #   -(1.0/6.0) * t1(e, m) * t1(a, n) * f1_OV(m, b) * t2(c, e, i, n)
    #   (1.0/6.0) * t1(e, m) * t1(a, n) * f1_OV(i, e) * t2(b, c, m, n)
    #   (1.0/6.0) * t1(e, m) * t1(a, n) * f1_OV(m, c) * t2(b, e, i, n)
    #   (1.0/2.0) * t1(a, m) * t1(e, n) * f1_OV(m, e) * t2(b, c, i, n)
    #   (1.0/3.0) * t2(e, a, m, n) * f1_OV(m, b) * t1(e, i) * t1(c, n)
    #   (1.0/3.0) * t2(e, a, m, n) * f1_OV(i, e) * t1(b, m) * t1(c, n)
    #   -(1.0/3.0) * t2(e, a, m, n) * f1_OV(m, c) * t1(b, n) * t1(e, i)

    #   PPPP -----------------------------------------------------------
    #   (1.0/4.0) * t2(c, d, m, n) * f1_OV(o, e) * t1(a, o) * t2(b, e, m, n)
    #   -(1.0/4.0) * t2(c, d, m, n) * f1_OV(o, e) * t1(b, o) * t2(a, e, m, n)
    #   (1.0/6.0) * t2(c, d, m, n) * f1_OV(o, e) * t1(a, m) * t2(b, e, n, o)
    #   -(1.0/6.0) * t2(e, d, m, n) * f1_OV(o, c) * t1(a, m) * t2(b, e, n, o)
    #   (1.0/6.0) * t2(e, c, m, n) * f1_OV(o, d) * t1(a, m) * t2(b, e, n, o)
    #   -(1.0/6.0) * t2(c, d, m, n) * f1_OV(o, e) * t1(b, m) * t2(a, e, n, o)
    #   (1.0/6.0) * t2(e, d, m, n) * f1_OV(o, c) * t1(b, m) * t2(a, e, n, o)
    #   -(1.0/6.0) * t2(e, c, m, n) * f1_OV(o, d) * t1(b, m) * t2(a, e, n, o)
    #   -(1.0/12.0) * t2(e, d, m, n) * f1_OV(o, c) * t1(e, o) * t2(a, b, m, n)
    #   (1.0/12.0) * t2(e, c, m, n) * f1_OV(o, d) * t1(e, o) * t2(a, b, m, n)
    #   (2.0/3.0) * t2(c, d, m, n) * f1_OV(o, e) * t1(e, m) * t2(a, b, n, o)
    #   -(1.0/6.0) * t2(e, d, m, n) * f1_OV(o, c) * t1(e, m) * t2(a, b, n, o)
    #   (1.0/6.0) * t2(e, c, m, n) * f1_OV(o, d) * t1(e, m) * t2(a, b, n, o)
    #   -(1.0/3.0) * f1_VV(a, e) * t1(c, m) * t1(d, n) * t2(b, e, m, n)
    #   (1.0/3.0) * f1_VV(b, e) * t1(c, m) * t1(d, n) * t2(a, e, m, n)
    #   (1.0/2.0) * t1(c, m) * t1(d, n) * f1_OO(o, m) * t2(a, b, n, o)
    #   -(1.0/2.0) * t1(d, m) * t1(c, n) * f1_OO(o, m) * t2(a, b, n, o)
    #   (1.0/6.0) * t1(e, m) * t1(d, n) * f1_VV(e, c) * t2(a, b, m, n)
    #   -(1.0/6.0) * t1(e, m) * t1(c, n) * f1_VV(e, d) * t2(a, b, m, n)
    #   -(1.0/6.0) * t2(c, d, m, n) * f1_VV(a, e) * t1(b, m) * t1(e, n)
    #   (1.0/6.0) * t2(c, d, m, n) * f1_VV(b, e) * t1(a, m) * t1(e, n)
    #   (1.0/2.0) * t2(c, d, m, n) * f1_OO(o, m) * t1(a, n) * t1(b, o)
    #   -(1.0/2.0) * t2(c, d, m, n) * f1_OO(o, m) * t1(a, o) * t1(b, n)
    #   -(1.0/3.0) * t2(e, c, m, n) * f1_VV(e, d) * t1(a, m) * t1(b, n)
    #   (1.0/3.0) * t2(e, d, m, n) * f1_VV(e, c) * t1(a, m) * t1(b, n)
    #   (1.0/12.0) * t1(e, m) * t2(c, d, n, o) * f1_OV(m, a) * t2(b, e, n, o)
    #   -(1.0/12.0) * t1(e, m) * t2(c, d, n, o) * f1_OV(m, b) * t2(a, e, n, o)
    #   -(1.0/6.0) * t1(d, m) * t2(e, c, n, o) * f1_OV(n, a) * t2(b, e, m, o)
    #   (1.0/6.0) * t1(c, m) * t2(e, d, n, o) * f1_OV(n, a) * t2(b, e, m, o)
    #   -(1.0/6.0) * t1(e, m) * t2(c, d, n, o) * f1_OV(n, a) * t2(b, e, m, o)
    #   (1.0/6.0) * t1(d, m) * t2(e, c, n, o) * f1_OV(n, b) * t2(a, e, m, o)
    #   -(1.0/6.0) * t1(c, m) * t2(e, d, n, o) * f1_OV(n, b) * t2(a, e, m, o)
    #   (1.0/6.0) * t1(e, m) * t2(c, d, n, o) * f1_OV(n, b) * t2(a, e, m, o)
    #   -(1.0/6.0) * t1(d, m) * t2(e, c, n, o) * f1_OV(n, e) * t2(a, b, m, o)
    #   (1.0/6.0) * t1(c, m) * t2(e, d, n, o) * f1_OV(n, e) * t2(a, b, m, o)
    #   -(1.0/4.0) * t1(c, m) * t2(e, d, n, o) * f1_OV(m, e) * t2(a, b, n, o)
    #   (1.0/4.0) * t1(d, m) * t2(e, c, n, o) * f1_OV(m, e) * t2(a, b, n, o)
    #   -(2.0/3.0) * t1(e, m) * t2(c, d, n, o) * f1_OV(n, e) * t2(a, b, m, o)

